// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pbvn_tsay
double pbvn_tsay(double h, double k, double rho);
RcppExport SEXP _EMC2_pbvn_tsay(SEXP hSEXP, SEXP kSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(pbvn_tsay(h, k, rho));
    return rcpp_result_gen;
END_RCPP
}
// pbvn_tvpack
double pbvn_tvpack(double h, double k, double rho);
RcppExport SEXP _EMC2_pbvn_tvpack(SEXP hSEXP, SEXP kSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(pbvn_tvpack(h, k, rho));
    return rcpp_result_gen;
END_RCPP
}
// pbvn_drezner
double pbvn_drezner(double h, double k, double rho);
RcppExport SEXP _EMC2_pbvn_drezner(SEXP hSEXP, SEXP kSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(pbvn_drezner(h, k, rho));
    return rcpp_result_gen;
END_RCPP
}
// sp_new
Rcpp::List sp_new(const int iter, const arma::cube& lambda_varimax, const int q, const int p, const int dim_all_c, const arma::mat& all_c, const arma::mat& lambda_hat, const arma::uvec& st, arma::mat cost_matrix, arma::mat perm);
RcppExport SEXP _EMC2_sp_new(SEXP iterSEXP, SEXP lambda_varimaxSEXP, SEXP qSEXP, SEXP pSEXP, SEXP dim_all_cSEXP, SEXP all_cSEXP, SEXP lambda_hatSEXP, SEXP stSEXP, SEXP cost_matrixSEXP, SEXP permSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type lambda_varimax(lambda_varimaxSEXP);
    Rcpp::traits::input_parameter< const int >::type q(qSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const int >::type dim_all_c(dim_all_cSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type all_c(all_cSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type lambda_hat(lambda_hatSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type st(stSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cost_matrix(cost_matrixSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type perm(permSEXP);
    rcpp_result_gen = Rcpp::wrap(sp_new(iter, lambda_varimax, q, p, dim_all_c, all_c, lambda_hat, st, cost_matrix, perm));
    return rcpp_result_gen;
END_RCPP
}
// calculate_subject_means
arma::mat calculate_subject_means(const Rcpp::List& group_designs, const arma::colvec& params, const int n_subjects, const int n_pars);
RcppExport SEXP _EMC2_calculate_subject_means(SEXP group_designsSEXP, SEXP paramsSEXP, SEXP n_subjectsSEXP, SEXP n_parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type group_designs(group_designsSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_subjects(n_subjectsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_pars(n_parsSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_subject_means(group_designs, params, n_subjects, n_pars));
    return rcpp_result_gen;
END_RCPP
}
// bm_fht_pdf_vec_grid
NumericVector bm_fht_pdf_vec_grid(NumericVector t, double mu, double sigma, double z0, double b0, double binf, double tau, double pow, double steps_fineness, double min_steps);
RcppExport SEXP _EMC2_bm_fht_pdf_vec_grid(SEXP tSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP z0SEXP, SEXP b0SEXP, SEXP binfSEXP, SEXP tauSEXP, SEXP powSEXP, SEXP steps_finenessSEXP, SEXP min_stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type binf(binfSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type pow(powSEXP);
    Rcpp::traits::input_parameter< double >::type steps_fineness(steps_finenessSEXP);
    Rcpp::traits::input_parameter< double >::type min_steps(min_stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(bm_fht_pdf_vec_grid(t, mu, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps));
    return rcpp_result_gen;
END_RCPP
}
// bm_fht_pdf_vec_grid_chunked
NumericVector bm_fht_pdf_vec_grid_chunked(NumericVector t, double mu, double sigma, double z0, double b0, double binf, double tau, double pow, double steps_fineness, double min_steps, double chunk_ratio, double chunk_base_panels, double chunk_max);
RcppExport SEXP _EMC2_bm_fht_pdf_vec_grid_chunked(SEXP tSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP z0SEXP, SEXP b0SEXP, SEXP binfSEXP, SEXP tauSEXP, SEXP powSEXP, SEXP steps_finenessSEXP, SEXP min_stepsSEXP, SEXP chunk_ratioSEXP, SEXP chunk_base_panelsSEXP, SEXP chunk_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type binf(binfSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type pow(powSEXP);
    Rcpp::traits::input_parameter< double >::type steps_fineness(steps_finenessSEXP);
    Rcpp::traits::input_parameter< double >::type min_steps(min_stepsSEXP);
    Rcpp::traits::input_parameter< double >::type chunk_ratio(chunk_ratioSEXP);
    Rcpp::traits::input_parameter< double >::type chunk_base_panels(chunk_base_panelsSEXP);
    Rcpp::traits::input_parameter< double >::type chunk_max(chunk_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(bm_fht_pdf_vec_grid_chunked(t, mu, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps, chunk_ratio, chunk_base_panels, chunk_max));
    return rcpp_result_gen;
END_RCPP
}
// bm_fht_cdf_vec_grid_chunked
NumericVector bm_fht_cdf_vec_grid_chunked(NumericVector t, double mu, double sigma, double z0, double b0, double binf, double tau, double pow, double steps_fineness, double min_steps, double chunk_ratio, double chunk_base_panels, double chunk_max, double rt_resolution);
RcppExport SEXP _EMC2_bm_fht_cdf_vec_grid_chunked(SEXP tSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP z0SEXP, SEXP b0SEXP, SEXP binfSEXP, SEXP tauSEXP, SEXP powSEXP, SEXP steps_finenessSEXP, SEXP min_stepsSEXP, SEXP chunk_ratioSEXP, SEXP chunk_base_panelsSEXP, SEXP chunk_maxSEXP, SEXP rt_resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type binf(binfSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type pow(powSEXP);
    Rcpp::traits::input_parameter< double >::type steps_fineness(steps_finenessSEXP);
    Rcpp::traits::input_parameter< double >::type min_steps(min_stepsSEXP);
    Rcpp::traits::input_parameter< double >::type chunk_ratio(chunk_ratioSEXP);
    Rcpp::traits::input_parameter< double >::type chunk_base_panels(chunk_base_panelsSEXP);
    Rcpp::traits::input_parameter< double >::type chunk_max(chunk_maxSEXP);
    Rcpp::traits::input_parameter< double >::type rt_resolution(rt_resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(bm_fht_cdf_vec_grid_chunked(t, mu, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps, chunk_ratio, chunk_base_panels, chunk_max, rt_resolution));
    return rcpp_result_gen;
END_RCPP
}
// bm_fht_cdf_vec_grid
NumericVector bm_fht_cdf_vec_grid(NumericVector t, double mu, double sigma, double z0, double b0, double binf, double tau, double pow, double steps_fineness, double min_steps, double rt_resolution);
RcppExport SEXP _EMC2_bm_fht_cdf_vec_grid(SEXP tSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP z0SEXP, SEXP b0SEXP, SEXP binfSEXP, SEXP tauSEXP, SEXP powSEXP, SEXP steps_finenessSEXP, SEXP min_stepsSEXP, SEXP rt_resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type binf(binfSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type pow(powSEXP);
    Rcpp::traits::input_parameter< double >::type steps_fineness(steps_finenessSEXP);
    Rcpp::traits::input_parameter< double >::type min_steps(min_stepsSEXP);
    Rcpp::traits::input_parameter< double >::type rt_resolution(rt_resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(bm_fht_cdf_vec_grid(t, mu, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps, rt_resolution));
    return rcpp_result_gen;
END_RCPP
}
// bm_fht_pdf_vec
NumericVector bm_fht_pdf_vec(NumericVector t, double mu, double sigma, double z0, double b0, double binf, double tau, double pow, int num_steps);
RcppExport SEXP _EMC2_bm_fht_pdf_vec(SEXP tSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP z0SEXP, SEXP b0SEXP, SEXP binfSEXP, SEXP tauSEXP, SEXP powSEXP, SEXP num_stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type binf(binfSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type pow(powSEXP);
    Rcpp::traits::input_parameter< int >::type num_steps(num_stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(bm_fht_pdf_vec(t, mu, sigma, z0, b0, binf, tau, pow, num_steps));
    return rcpp_result_gen;
END_RCPP
}
// bm_fht_cdf_vec
NumericVector bm_fht_cdf_vec(NumericVector t, double mu, double sigma, double z0, double b0, double binf, double tau, double pow, int num_steps);
RcppExport SEXP _EMC2_bm_fht_cdf_vec(SEXP tSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP z0SEXP, SEXP b0SEXP, SEXP binfSEXP, SEXP tauSEXP, SEXP powSEXP, SEXP num_stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type binf(binfSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type pow(powSEXP);
    Rcpp::traits::input_parameter< int >::type num_steps(num_stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(bm_fht_cdf_vec(t, mu, sigma, z0, b0, binf, tau, pow, num_steps));
    return rcpp_result_gen;
END_RCPP
}
// simulate_bm_hit_times
Rcpp::NumericVector simulate_bm_hit_times(int n, double mu, double sigma, double z0, double b0, double binf, double tau, double pow, double dt, double t_max);
RcppExport SEXP _EMC2_simulate_bm_hit_times(SEXP nSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP z0SEXP, SEXP b0SEXP, SEXP binfSEXP, SEXP tauSEXP, SEXP powSEXP, SEXP dtSEXP, SEXP t_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type binf(binfSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type pow(powSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type t_max(t_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_bm_hit_times(n, mu, sigma, z0, b0, binf, tau, pow, dt, t_max));
    return rcpp_result_gen;
END_RCPP
}
// simulate_bm_hit_times_bb
Rcpp::NumericVector simulate_bm_hit_times_bb(int n, double mu, double sigma, double z0, double b0, double binf, double tau, double pow, double dt, double t_max);
RcppExport SEXP _EMC2_simulate_bm_hit_times_bb(SEXP nSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP z0SEXP, SEXP b0SEXP, SEXP binfSEXP, SEXP tauSEXP, SEXP powSEXP, SEXP dtSEXP, SEXP t_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type binf(binfSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type pow(powSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type t_max(t_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_bm_hit_times_bb(n, mu, sigma, z0, b0, binf, tau, pow, dt, t_max));
    return rcpp_result_gen;
END_RCPP
}
// plba_norm
double plba_norm(double t, double A, double b, double v, double sv, bool posdrift, bool log_out);
RcppExport SEXP _EMC2_plba_norm(SEXP tSEXP, SEXP ASEXP, SEXP bSEXP, SEXP vSEXP, SEXP svSEXP, SEXP posdriftSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type sv(svSEXP);
    Rcpp::traits::input_parameter< bool >::type posdrift(posdriftSEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(plba_norm(t, A, b, v, sv, posdrift, log_out));
    return rcpp_result_gen;
END_RCPP
}
// dlba_norm
double dlba_norm(double t, double A, double b, double v, double sv, bool posdrift, bool log_out);
RcppExport SEXP _EMC2_dlba_norm(SEXP tSEXP, SEXP ASEXP, SEXP bSEXP, SEXP vSEXP, SEXP svSEXP, SEXP posdriftSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type sv(svSEXP);
    Rcpp::traits::input_parameter< bool >::type posdrift(posdriftSEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(dlba_norm(t, A, b, v, sv, posdrift, log_out));
    return rcpp_result_gen;
END_RCPP
}
// dlba_c
NumericVector dlba_c(NumericVector rts, NumericMatrix pars, LogicalVector idx, double min_ll, LogicalVector is_ok, bool use_posdrift, bool log_out);
RcppExport SEXP _EMC2_dlba_c(SEXP rtsSEXP, SEXP parsSEXP, SEXP idxSEXP, SEXP min_llSEXP, SEXP is_okSEXP, SEXP use_posdriftSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rts(rtsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< double >::type min_ll(min_llSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_ok(is_okSEXP);
    Rcpp::traits::input_parameter< bool >::type use_posdrift(use_posdriftSEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(dlba_c(rts, pars, idx, min_ll, is_ok, use_posdrift, log_out));
    return rcpp_result_gen;
END_RCPP
}
// plba_c
NumericVector plba_c(NumericVector rts, NumericMatrix pars, LogicalVector idx, double min_ll, LogicalVector is_ok, bool use_posdrift, bool log_out);
RcppExport SEXP _EMC2_plba_c(SEXP rtsSEXP, SEXP parsSEXP, SEXP idxSEXP, SEXP min_llSEXP, SEXP is_okSEXP, SEXP use_posdriftSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rts(rtsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< double >::type min_ll(min_llSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_ok(is_okSEXP);
    Rcpp::traits::input_parameter< bool >::type use_posdrift(use_posdriftSEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(plba_c(rts, pars, idx, min_ll, is_ok, use_posdrift, log_out));
    return rcpp_result_gen;
END_RCPP
}
// dlba_joint_c
NumericVector dlba_joint_c(NumericVector rts, NumericMatrix pars, LogicalVector idx, double min_ll, LogicalVector is_ok, bool use_posdrift, bool log_out);
RcppExport SEXP _EMC2_dlba_joint_c(SEXP rtsSEXP, SEXP parsSEXP, SEXP idxSEXP, SEXP min_llSEXP, SEXP is_okSEXP, SEXP use_posdriftSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rts(rtsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< double >::type min_ll(min_llSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_ok(is_okSEXP);
    Rcpp::traits::input_parameter< bool >::type use_posdrift(use_posdriftSEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(dlba_joint_c(rts, pars, idx, min_ll, is_ok, use_posdrift, log_out));
    return rcpp_result_gen;
END_RCPP
}
// plba_joint_c
NumericVector plba_joint_c(NumericVector rts, NumericMatrix pars, LogicalVector idx, double min_ll, LogicalVector is_ok, bool use_posdrift, bool log_out);
RcppExport SEXP _EMC2_plba_joint_c(SEXP rtsSEXP, SEXP parsSEXP, SEXP idxSEXP, SEXP min_llSEXP, SEXP is_okSEXP, SEXP use_posdriftSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rts(rtsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< double >::type min_ll(min_llSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_ok(is_okSEXP);
    Rcpp::traits::input_parameter< bool >::type use_posdrift(use_posdriftSEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(plba_joint_c(rts, pars, idx, min_ll, is_ok, use_posdrift, log_out));
    return rcpp_result_gen;
END_RCPP
}
// dlba
NumericVector dlba(NumericVector t, NumericVector A, NumericVector b, NumericVector v, NumericVector sv, bool posdrift);
RcppExport SEXP _EMC2_dlba(SEXP tSEXP, SEXP ASEXP, SEXP bSEXP, SEXP vSEXP, SEXP svSEXP, SEXP posdriftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sv(svSEXP);
    Rcpp::traits::input_parameter< bool >::type posdrift(posdriftSEXP);
    rcpp_result_gen = Rcpp::wrap(dlba(t, A, b, v, sv, posdrift));
    return rcpp_result_gen;
END_RCPP
}
// plba
NumericVector plba(NumericVector t, NumericVector A, NumericVector b, NumericVector v, NumericVector sv, bool posdrift);
RcppExport SEXP _EMC2_plba(SEXP tSEXP, SEXP ASEXP, SEXP bSEXP, SEXP vSEXP, SEXP svSEXP, SEXP posdriftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sv(svSEXP);
    Rcpp::traits::input_parameter< bool >::type posdrift(posdriftSEXP);
    rcpp_result_gen = Rcpp::wrap(plba(t, A, b, v, sv, posdrift));
    return rcpp_result_gen;
END_RCPP
}
// ou_fht_cdf
double ou_fht_cdf(double t, double lambda, double theta, double sigma, double z0, double b0, double binf, double tau, double p, int num_steps);
RcppExport SEXP _EMC2_ou_fht_cdf(SEXP tSEXP, SEXP lambdaSEXP, SEXP thetaSEXP, SEXP sigmaSEXP, SEXP z0SEXP, SEXP b0SEXP, SEXP binfSEXP, SEXP tauSEXP, SEXP pSEXP, SEXP num_stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type binf(binfSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type num_steps(num_stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(ou_fht_cdf(t, lambda, theta, sigma, z0, b0, binf, tau, p, num_steps));
    return rcpp_result_gen;
END_RCPP
}
// ou_fht_pdf_vec
NumericVector ou_fht_pdf_vec(NumericVector t, double lambda, double theta, double sigma, double z0, double b0, double binf, double tau, double pow, double steps_fineness, double min_steps);
RcppExport SEXP _EMC2_ou_fht_pdf_vec(SEXP tSEXP, SEXP lambdaSEXP, SEXP thetaSEXP, SEXP sigmaSEXP, SEXP z0SEXP, SEXP b0SEXP, SEXP binfSEXP, SEXP tauSEXP, SEXP powSEXP, SEXP steps_finenessSEXP, SEXP min_stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type binf(binfSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type pow(powSEXP);
    Rcpp::traits::input_parameter< double >::type steps_fineness(steps_finenessSEXP);
    Rcpp::traits::input_parameter< double >::type min_steps(min_stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(ou_fht_pdf_vec(t, lambda, theta, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps));
    return rcpp_result_gen;
END_RCPP
}
// ou_fht_cdf_vec_grid
NumericVector ou_fht_cdf_vec_grid(NumericVector t, double lambda, double theta, double sigma, double z0, double b0, double binf, double tau, double pow, double steps_fineness, double min_steps, double min_t_fineness, double rt_resolution);
RcppExport SEXP _EMC2_ou_fht_cdf_vec_grid(SEXP tSEXP, SEXP lambdaSEXP, SEXP thetaSEXP, SEXP sigmaSEXP, SEXP z0SEXP, SEXP b0SEXP, SEXP binfSEXP, SEXP tauSEXP, SEXP powSEXP, SEXP steps_finenessSEXP, SEXP min_stepsSEXP, SEXP min_t_finenessSEXP, SEXP rt_resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type binf(binfSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type pow(powSEXP);
    Rcpp::traits::input_parameter< double >::type steps_fineness(steps_finenessSEXP);
    Rcpp::traits::input_parameter< double >::type min_steps(min_stepsSEXP);
    Rcpp::traits::input_parameter< double >::type min_t_fineness(min_t_finenessSEXP);
    Rcpp::traits::input_parameter< double >::type rt_resolution(rt_resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(ou_fht_cdf_vec_grid(t, lambda, theta, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps, min_t_fineness, rt_resolution));
    return rcpp_result_gen;
END_RCPP
}
// ou_fht_pdf_vec_spline
NumericVector ou_fht_pdf_vec_spline(NumericVector t, double lambda, double theta, double sigma, double z0, double b0, double binf, double tau, double pow, double steps_fineness, double min_steps);
RcppExport SEXP _EMC2_ou_fht_pdf_vec_spline(SEXP tSEXP, SEXP lambdaSEXP, SEXP thetaSEXP, SEXP sigmaSEXP, SEXP z0SEXP, SEXP b0SEXP, SEXP binfSEXP, SEXP tauSEXP, SEXP powSEXP, SEXP steps_finenessSEXP, SEXP min_stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type binf(binfSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type pow(powSEXP);
    Rcpp::traits::input_parameter< double >::type steps_fineness(steps_finenessSEXP);
    Rcpp::traits::input_parameter< double >::type min_steps(min_stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(ou_fht_pdf_vec_spline(t, lambda, theta, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps));
    return rcpp_result_gen;
END_RCPP
}
// ou_fht_cdf_vec
NumericVector ou_fht_cdf_vec(NumericVector t, double lambda, double theta, double sigma, double z0, double b0, double binf, double tau, double pow, int num_steps);
RcppExport SEXP _EMC2_ou_fht_cdf_vec(SEXP tSEXP, SEXP lambdaSEXP, SEXP thetaSEXP, SEXP sigmaSEXP, SEXP z0SEXP, SEXP b0SEXP, SEXP binfSEXP, SEXP tauSEXP, SEXP powSEXP, SEXP num_stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type binf(binfSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type pow(powSEXP);
    Rcpp::traits::input_parameter< int >::type num_steps(num_stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(ou_fht_cdf_vec(t, lambda, theta, sigma, z0, b0, binf, tau, pow, num_steps));
    return rcpp_result_gen;
END_RCPP
}
// ou_fht_pdf_vec_closed_form
NumericVector ou_fht_pdf_vec_closed_form(NumericVector t, double lambda, double theta, double sigma, double z0, double b0, double binf, double tau, double pow);
RcppExport SEXP _EMC2_ou_fht_pdf_vec_closed_form(SEXP tSEXP, SEXP lambdaSEXP, SEXP thetaSEXP, SEXP sigmaSEXP, SEXP z0SEXP, SEXP b0SEXP, SEXP binfSEXP, SEXP tauSEXP, SEXP powSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type binf(binfSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type pow(powSEXP);
    rcpp_result_gen = Rcpp::wrap(ou_fht_pdf_vec_closed_form(t, lambda, theta, sigma, z0, b0, binf, tau, pow));
    return rcpp_result_gen;
END_RCPP
}
// ou_fht_cdf_vec_closed_form
NumericVector ou_fht_cdf_vec_closed_form(NumericVector t, double lambda, double theta, double sigma, double z0, double b0, double binf, double tau, double pow);
RcppExport SEXP _EMC2_ou_fht_cdf_vec_closed_form(SEXP tSEXP, SEXP lambdaSEXP, SEXP thetaSEXP, SEXP sigmaSEXP, SEXP z0SEXP, SEXP b0SEXP, SEXP binfSEXP, SEXP tauSEXP, SEXP powSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type binf(binfSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type pow(powSEXP);
    rcpp_result_gen = Rcpp::wrap(ou_fht_cdf_vec_closed_form(t, lambda, theta, sigma, z0, b0, binf, tau, pow));
    return rcpp_result_gen;
END_RCPP
}
// ou_fht_pdf_vec_grid
NumericVector ou_fht_pdf_vec_grid(NumericVector t, double lambda, double theta, double sigma, double z0, double b0, double binf, double tau, double pow, double steps_fineness, double min_steps, double min_t_fineness);
RcppExport SEXP _EMC2_ou_fht_pdf_vec_grid(SEXP tSEXP, SEXP lambdaSEXP, SEXP thetaSEXP, SEXP sigmaSEXP, SEXP z0SEXP, SEXP b0SEXP, SEXP binfSEXP, SEXP tauSEXP, SEXP powSEXP, SEXP steps_finenessSEXP, SEXP min_stepsSEXP, SEXP min_t_finenessSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type binf(binfSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type pow(powSEXP);
    Rcpp::traits::input_parameter< double >::type steps_fineness(steps_finenessSEXP);
    Rcpp::traits::input_parameter< double >::type min_steps(min_stepsSEXP);
    Rcpp::traits::input_parameter< double >::type min_t_fineness(min_t_finenessSEXP);
    rcpp_result_gen = Rcpp::wrap(ou_fht_pdf_vec_grid(t, lambda, theta, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps, min_t_fineness));
    return rcpp_result_gen;
END_RCPP
}
// ou_fht_pdf_vec_grid_chunked
NumericVector ou_fht_pdf_vec_grid_chunked(NumericVector t, double lambda, double theta, double sigma, double z0, double b0, double binf, double tau, double pow, double steps_fineness, double min_steps, double min_t_fineness, double chunk_ratio, double chunk_base_panels, double chunk_max);
RcppExport SEXP _EMC2_ou_fht_pdf_vec_grid_chunked(SEXP tSEXP, SEXP lambdaSEXP, SEXP thetaSEXP, SEXP sigmaSEXP, SEXP z0SEXP, SEXP b0SEXP, SEXP binfSEXP, SEXP tauSEXP, SEXP powSEXP, SEXP steps_finenessSEXP, SEXP min_stepsSEXP, SEXP min_t_finenessSEXP, SEXP chunk_ratioSEXP, SEXP chunk_base_panelsSEXP, SEXP chunk_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type binf(binfSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type pow(powSEXP);
    Rcpp::traits::input_parameter< double >::type steps_fineness(steps_finenessSEXP);
    Rcpp::traits::input_parameter< double >::type min_steps(min_stepsSEXP);
    Rcpp::traits::input_parameter< double >::type min_t_fineness(min_t_finenessSEXP);
    Rcpp::traits::input_parameter< double >::type chunk_ratio(chunk_ratioSEXP);
    Rcpp::traits::input_parameter< double >::type chunk_base_panels(chunk_base_panelsSEXP);
    Rcpp::traits::input_parameter< double >::type chunk_max(chunk_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(ou_fht_pdf_vec_grid_chunked(t, lambda, theta, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps, min_t_fineness, chunk_ratio, chunk_base_panels, chunk_max));
    return rcpp_result_gen;
END_RCPP
}
// simulate_ou_hit_times_std
NumericVector simulate_ou_hit_times_std(int n, double lambda, double theta, double sigma, double z0, double b0, double binf, double tau, double p, double dt, double t_max);
RcppExport SEXP _EMC2_simulate_ou_hit_times_std(SEXP nSEXP, SEXP lambdaSEXP, SEXP thetaSEXP, SEXP sigmaSEXP, SEXP z0SEXP, SEXP b0SEXP, SEXP binfSEXP, SEXP tauSEXP, SEXP pSEXP, SEXP dtSEXP, SEXP t_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type binf(binfSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type t_max(t_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_ou_hit_times_std(n, lambda, theta, sigma, z0, b0, binf, tau, p, dt, t_max));
    return rcpp_result_gen;
END_RCPP
}
// ou_fht_cdf_vec_grid_chunked
NumericVector ou_fht_cdf_vec_grid_chunked(NumericVector t, double lambda, double theta, double sigma, double z0, double b0, double binf, double tau, double pow, double steps_fineness, double min_steps, double min_t_fineness, double chunk_ratio, double chunk_base_panels, double chunk_max, double rt_resolution);
RcppExport SEXP _EMC2_ou_fht_cdf_vec_grid_chunked(SEXP tSEXP, SEXP lambdaSEXP, SEXP thetaSEXP, SEXP sigmaSEXP, SEXP z0SEXP, SEXP b0SEXP, SEXP binfSEXP, SEXP tauSEXP, SEXP powSEXP, SEXP steps_finenessSEXP, SEXP min_stepsSEXP, SEXP min_t_finenessSEXP, SEXP chunk_ratioSEXP, SEXP chunk_base_panelsSEXP, SEXP chunk_maxSEXP, SEXP rt_resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type binf(binfSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type pow(powSEXP);
    Rcpp::traits::input_parameter< double >::type steps_fineness(steps_finenessSEXP);
    Rcpp::traits::input_parameter< double >::type min_steps(min_stepsSEXP);
    Rcpp::traits::input_parameter< double >::type min_t_fineness(min_t_finenessSEXP);
    Rcpp::traits::input_parameter< double >::type chunk_ratio(chunk_ratioSEXP);
    Rcpp::traits::input_parameter< double >::type chunk_base_panels(chunk_base_panelsSEXP);
    Rcpp::traits::input_parameter< double >::type chunk_max(chunk_maxSEXP);
    Rcpp::traits::input_parameter< double >::type rt_resolution(rt_resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(ou_fht_cdf_vec_grid_chunked(t, lambda, theta, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps, min_t_fineness, chunk_ratio, chunk_base_panels, chunk_max, rt_resolution));
    return rcpp_result_gen;
END_RCPP
}
// simulate_ou_hit_times
NumericVector simulate_ou_hit_times(int n, double lambda, double theta, double sigma, double z0, double b0, double binf, double tau, double p, double dt, double t_max);
RcppExport SEXP _EMC2_simulate_ou_hit_times(SEXP nSEXP, SEXP lambdaSEXP, SEXP thetaSEXP, SEXP sigmaSEXP, SEXP z0SEXP, SEXP b0SEXP, SEXP binfSEXP, SEXP tauSEXP, SEXP pSEXP, SEXP dtSEXP, SEXP t_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type binf(binfSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type t_max(t_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_ou_hit_times(n, lambda, theta, sigma, z0, b0, binf, tau, p, dt, t_max));
    return rcpp_result_gen;
END_RCPP
}
// simulate_ou_hit_times_bb
NumericVector simulate_ou_hit_times_bb(int n, double lambda, double theta, double sigma, double z0, double b0, double binf, double tau, double p, double dt, double t_max, double p_tol, double eps_curv, double adapt_factor, bool adaptive);
RcppExport SEXP _EMC2_simulate_ou_hit_times_bb(SEXP nSEXP, SEXP lambdaSEXP, SEXP thetaSEXP, SEXP sigmaSEXP, SEXP z0SEXP, SEXP b0SEXP, SEXP binfSEXP, SEXP tauSEXP, SEXP pSEXP, SEXP dtSEXP, SEXP t_maxSEXP, SEXP p_tolSEXP, SEXP eps_curvSEXP, SEXP adapt_factorSEXP, SEXP adaptiveSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type binf(binfSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type t_max(t_maxSEXP);
    Rcpp::traits::input_parameter< double >::type p_tol(p_tolSEXP);
    Rcpp::traits::input_parameter< double >::type eps_curv(eps_curvSEXP);
    Rcpp::traits::input_parameter< double >::type adapt_factor(adapt_factorSEXP);
    Rcpp::traits::input_parameter< bool >::type adaptive(adaptiveSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_ou_hit_times_bb(n, lambda, theta, sigma, z0, b0, binf, tau, p, dt, t_max, p_tol, eps_curv, adapt_factor, adaptive));
    return rcpp_result_gen;
END_RCPP
}
// pigt0
double pigt0(double t, double k, double l, bool log_out);
RcppExport SEXP _EMC2_pigt0(SEXP tSEXP, SEXP kSEXP, SEXP lSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(pigt0(t, k, l, log_out));
    return rcpp_result_gen;
END_RCPP
}
// digt0
double digt0(double t, double k, double l, bool log_out);
RcppExport SEXP _EMC2_digt0(SEXP tSEXP, SEXP kSEXP, SEXP lSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(digt0(t, k, l, log_out));
    return rcpp_result_gen;
END_RCPP
}
// dwald_classic
double dwald_classic(double t, double boundary_alpha, double drift_rate_xi, bool log_out);
RcppExport SEXP _EMC2_dwald_classic(SEXP tSEXP, SEXP boundary_alphaSEXP, SEXP drift_rate_xiSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type boundary_alpha(boundary_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type drift_rate_xi(drift_rate_xiSEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(dwald_classic(t, boundary_alpha, drift_rate_xi, log_out));
    return rcpp_result_gen;
END_RCPP
}
// pwald_classic
double pwald_classic(double t, double boundary_alpha, double drift_rate_xi, bool log_out);
RcppExport SEXP _EMC2_pwald_classic(SEXP tSEXP, SEXP boundary_alphaSEXP, SEXP drift_rate_xiSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type boundary_alpha(boundary_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type drift_rate_xi(drift_rate_xiSEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(pwald_classic(t, boundary_alpha, drift_rate_xi, log_out));
    return rcpp_result_gen;
END_RCPP
}
// pigt
double pigt(double t, double k, double l, double a, double threshold, bool log_out);
RcppExport SEXP _EMC2_pigt(SEXP tSEXP, SEXP kSEXP, SEXP lSEXP, SEXP aSEXP, SEXP thresholdSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(pigt(t, k, l, a, threshold, log_out));
    return rcpp_result_gen;
END_RCPP
}
// digt
double digt(double t, double k, double l, double a, double threshold, bool log_out);
RcppExport SEXP _EMC2_digt(SEXP tSEXP, SEXP kSEXP, SEXP lSEXP, SEXP aSEXP, SEXP thresholdSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(digt(t, k, l, a, threshold, log_out));
    return rcpp_result_gen;
END_RCPP
}
// drdm_c
NumericVector drdm_c(NumericVector rts, NumericMatrix pars, LogicalVector idx, double min_ll, LogicalVector is_ok, bool log_out);
RcppExport SEXP _EMC2_drdm_c(SEXP rtsSEXP, SEXP parsSEXP, SEXP idxSEXP, SEXP min_llSEXP, SEXP is_okSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rts(rtsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< double >::type min_ll(min_llSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_ok(is_okSEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(drdm_c(rts, pars, idx, min_ll, is_ok, log_out));
    return rcpp_result_gen;
END_RCPP
}
// prdm_c
NumericVector prdm_c(NumericVector rts, NumericMatrix pars, LogicalVector idx, double min_ll, LogicalVector is_ok, bool log_out);
RcppExport SEXP _EMC2_prdm_c(SEXP rtsSEXP, SEXP parsSEXP, SEXP idxSEXP, SEXP min_llSEXP, SEXP is_okSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rts(rtsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< double >::type min_ll(min_llSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_ok(is_okSEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(prdm_c(rts, pars, idx, min_ll, is_ok, log_out));
    return rcpp_result_gen;
END_RCPP
}
// dRDM_c
NumericVector dRDM_c(NumericVector t, NumericVector v, NumericVector B, NumericVector A, NumericVector t0, bool log_out);
RcppExport SEXP _EMC2_dRDM_c(SEXP tSEXP, SEXP vSEXP, SEXP BSEXP, SEXP ASEXP, SEXP t0SEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(dRDM_c(t, v, B, A, t0, log_out));
    return rcpp_result_gen;
END_RCPP
}
// pRDM_c
NumericVector pRDM_c(NumericVector t, NumericVector v, NumericVector B, NumericVector A, NumericVector t0, bool log_out);
RcppExport SEXP _EMC2_pRDM_c(SEXP tSEXP, SEXP vSEXP, SEXP BSEXP, SEXP ASEXP, SEXP t0SEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(pRDM_c(t, v, B, A, t0, log_out));
    return rcpp_result_gen;
END_RCPP
}
// dswtn
double dswtn(double t_adj, double alpha, double mu_drift, double sigma_drift, bool log_out);
RcppExport SEXP _EMC2_dswtn(SEXP t_adjSEXP, SEXP alphaSEXP, SEXP mu_driftSEXP, SEXP sigma_driftSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t_adj(t_adjSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type mu_drift(mu_driftSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_drift(sigma_driftSEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(dswtn(t_adj, alpha, mu_drift, sigma_drift, log_out));
    return rcpp_result_gen;
END_RCPP
}
// pswtn
double pswtn(double t_adj, double alpha, double mu_drift, double sigma_drift, bool log_out);
RcppExport SEXP _EMC2_pswtn(SEXP t_adjSEXP, SEXP alphaSEXP, SEXP mu_driftSEXP, SEXP sigma_driftSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t_adj(t_adjSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type mu_drift(mu_driftSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_drift(sigma_driftSEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(pswtn(t_adj, alpha, mu_drift, sigma_drift, log_out));
    return rcpp_result_gen;
END_RCPP
}
// drdmswtn
double drdmswtn(double t_adj, double b, double mu_drift, double A, double sigma_drift, int n_gauss_nodes, bool log_out);
RcppExport SEXP _EMC2_drdmswtn(SEXP t_adjSEXP, SEXP bSEXP, SEXP mu_driftSEXP, SEXP ASEXP, SEXP sigma_driftSEXP, SEXP n_gauss_nodesSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t_adj(t_adjSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type mu_drift(mu_driftSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type sigma_drift(sigma_driftSEXP);
    Rcpp::traits::input_parameter< int >::type n_gauss_nodes(n_gauss_nodesSEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(drdmswtn(t_adj, b, mu_drift, A, sigma_drift, n_gauss_nodes, log_out));
    return rcpp_result_gen;
END_RCPP
}
// prdmswtn
double prdmswtn(double t_adj, double b, double mu_drift, double A, double sigma_drift, int n_gauss_nodes, bool log_out);
RcppExport SEXP _EMC2_prdmswtn(SEXP t_adjSEXP, SEXP bSEXP, SEXP mu_driftSEXP, SEXP ASEXP, SEXP sigma_driftSEXP, SEXP n_gauss_nodesSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t_adj(t_adjSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type mu_drift(mu_driftSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type sigma_drift(sigma_driftSEXP);
    Rcpp::traits::input_parameter< int >::type n_gauss_nodes(n_gauss_nodesSEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(prdmswtn(t_adj, b, mu_drift, A, sigma_drift, n_gauss_nodes, log_out));
    return rcpp_result_gen;
END_RCPP
}
// dSWTNspv
NumericVector dSWTNspv(NumericVector t, NumericVector v, NumericVector b, NumericVector A, NumericVector t0, NumericVector sv, bool log_out);
RcppExport SEXP _EMC2_dSWTNspv(SEXP tSEXP, SEXP vSEXP, SEXP bSEXP, SEXP ASEXP, SEXP t0SEXP, SEXP svSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sv(svSEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(dSWTNspv(t, v, b, A, t0, sv, log_out));
    return rcpp_result_gen;
END_RCPP
}
// pSWTNspv
NumericVector pSWTNspv(NumericVector t, NumericVector v, NumericVector b, NumericVector A, NumericVector t0, NumericVector sv, bool log_out);
RcppExport SEXP _EMC2_pSWTNspv(SEXP tSEXP, SEXP vSEXP, SEXP bSEXP, SEXP ASEXP, SEXP t0SEXP, SEXP svSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sv(svSEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(pSWTNspv(t, v, b, A, t0, sv, log_out));
    return rcpp_result_gen;
END_RCPP
}
// drdmswtn_c
NumericVector drdmswtn_c(NumericVector rts, NumericMatrix pars, LogicalVector idx, double min_ll, LogicalVector is_ok, bool log_out);
RcppExport SEXP _EMC2_drdmswtn_c(SEXP rtsSEXP, SEXP parsSEXP, SEXP idxSEXP, SEXP min_llSEXP, SEXP is_okSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rts(rtsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< double >::type min_ll(min_llSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_ok(is_okSEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(drdmswtn_c(rts, pars, idx, min_ll, is_ok, log_out));
    return rcpp_result_gen;
END_RCPP
}
// prdmswtn_c
NumericVector prdmswtn_c(NumericVector rts, NumericMatrix pars, LogicalVector idx, double min_ll, LogicalVector is_ok, bool log_out);
RcppExport SEXP _EMC2_prdmswtn_c(SEXP rtsSEXP, SEXP parsSEXP, SEXP idxSEXP, SEXP min_llSEXP, SEXP is_okSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rts(rtsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< double >::type min_ll(min_llSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_ok(is_okSEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(prdmswtn_c(rts, pars, idx, min_ll, is_ok, log_out));
    return rcpp_result_gen;
END_RCPP
}
// pswtn_numeric_integral
double pswtn_numeric_integral(double t_adj, double alpha, double mu_drift, double sigma_drift, double abs_err, double rel_err, size_t max_eval);
RcppExport SEXP _EMC2_pswtn_numeric_integral(SEXP t_adjSEXP, SEXP alphaSEXP, SEXP mu_driftSEXP, SEXP sigma_driftSEXP, SEXP abs_errSEXP, SEXP rel_errSEXP, SEXP max_evalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t_adj(t_adjSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type mu_drift(mu_driftSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_drift(sigma_driftSEXP);
    Rcpp::traits::input_parameter< double >::type abs_err(abs_errSEXP);
    Rcpp::traits::input_parameter< double >::type rel_err(rel_errSEXP);
    Rcpp::traits::input_parameter< size_t >::type max_eval(max_evalSEXP);
    rcpp_result_gen = Rcpp::wrap(pswtn_numeric_integral(t_adj, alpha, mu_drift, sigma_drift, abs_err, rel_err, max_eval));
    return rcpp_result_gen;
END_RCPP
}
// drdmswtn_numeric_integral
double drdmswtn_numeric_integral(double t_adj, double b, double mu_drift, double A, double sigma_drift, double spv_abs_err, double spv_rel_err, size_t spv_max_eval);
RcppExport SEXP _EMC2_drdmswtn_numeric_integral(SEXP t_adjSEXP, SEXP bSEXP, SEXP mu_driftSEXP, SEXP ASEXP, SEXP sigma_driftSEXP, SEXP spv_abs_errSEXP, SEXP spv_rel_errSEXP, SEXP spv_max_evalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t_adj(t_adjSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type mu_drift(mu_driftSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type sigma_drift(sigma_driftSEXP);
    Rcpp::traits::input_parameter< double >::type spv_abs_err(spv_abs_errSEXP);
    Rcpp::traits::input_parameter< double >::type spv_rel_err(spv_rel_errSEXP);
    Rcpp::traits::input_parameter< size_t >::type spv_max_eval(spv_max_evalSEXP);
    rcpp_result_gen = Rcpp::wrap(drdmswtn_numeric_integral(t_adj, b, mu_drift, A, sigma_drift, spv_abs_err, spv_rel_err, spv_max_eval));
    return rcpp_result_gen;
END_RCPP
}
// prdmswtn_numeric_integral
double prdmswtn_numeric_integral(double t_adj, double b, double mu_drift, double A, double sigma_drift, double spv_abs_err, double spv_rel_err, size_t spv_max_eval);
RcppExport SEXP _EMC2_prdmswtn_numeric_integral(SEXP t_adjSEXP, SEXP bSEXP, SEXP mu_driftSEXP, SEXP ASEXP, SEXP sigma_driftSEXP, SEXP spv_abs_errSEXP, SEXP spv_rel_errSEXP, SEXP spv_max_evalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t_adj(t_adjSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type mu_drift(mu_driftSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type sigma_drift(sigma_driftSEXP);
    Rcpp::traits::input_parameter< double >::type spv_abs_err(spv_abs_errSEXP);
    Rcpp::traits::input_parameter< double >::type spv_rel_err(spv_rel_errSEXP);
    Rcpp::traits::input_parameter< size_t >::type spv_max_eval(spv_max_evalSEXP);
    rcpp_result_gen = Rcpp::wrap(prdmswtn_numeric_integral(t_adj, b, mu_drift, A, sigma_drift, spv_abs_err, spv_rel_err, spv_max_eval));
    return rcpp_result_gen;
END_RCPP
}
// pEXG
NumericVector pEXG(NumericVector q, double mu, double sigma, double tau, bool lower_tail, bool log_p);
RcppExport SEXP _EMC2_pEXG(SEXP qSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP tauSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(pEXG(q, mu, sigma, tau, lower_tail, log_p));
    return rcpp_result_gen;
END_RCPP
}
// dEXG
NumericVector dEXG(NumericVector x, double mu, double sigma, double tau, bool log_d);
RcppExport SEXP _EMC2_dEXG(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP tauSEXP, SEXP log_dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< bool >::type log_d(log_dSEXP);
    rcpp_result_gen = Rcpp::wrap(dEXG(x, mu, sigma, tau, log_d));
    return rcpp_result_gen;
END_RCPP
}
// dEXGrace
NumericVector dEXGrace(NumericMatrix dt, NumericVector mu, NumericVector sigma, NumericVector tau);
RcppExport SEXP _EMC2_dEXGrace(SEXP dtSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(dEXGrace(dt, mu, sigma, tau));
    return rcpp_result_gen;
END_RCPP
}
// stopfn_exg
NumericVector stopfn_exg(NumericVector t, NumericVector mu, NumericVector sigma, NumericVector tau, double SSD);
RcppExport SEXP _EMC2_stopfn_exg(SEXP tSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP tauSEXP, SEXP SSDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type SSD(SSDSEXP);
    rcpp_result_gen = Rcpp::wrap(stopfn_exg(t, mu, sigma, tau, SSD));
    return rcpp_result_gen;
END_RCPP
}
// pEXG_RDEX
NumericVector pEXG_RDEX(NumericVector q, double mu, double sigma, double tau, bool lower_tail, bool log_p);
RcppExport SEXP _EMC2_pEXG_RDEX(SEXP qSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP tauSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(pEXG_RDEX(q, mu, sigma, tau, lower_tail, log_p));
    return rcpp_result_gen;
END_RCPP
}
// dEXG_RDEX
NumericVector dEXG_RDEX(NumericVector x, double mu, double sigma, double tau, bool log_d);
RcppExport SEXP _EMC2_dEXG_RDEX(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP tauSEXP, SEXP log_dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< bool >::type log_d(log_dSEXP);
    rcpp_result_gen = Rcpp::wrap(dEXG_RDEX(x, mu, sigma, tau, log_d));
    return rcpp_result_gen;
END_RCPP
}
// pigt0_RDEX
double pigt0_RDEX(double t, double k, double l);
RcppExport SEXP _EMC2_pigt0_RDEX(SEXP tSEXP, SEXP kSEXP, SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(pigt0_RDEX(t, k, l));
    return rcpp_result_gen;
END_RCPP
}
// digt0_RDEX
double digt0_RDEX(double t, double k, double l);
RcppExport SEXP _EMC2_digt0_RDEX(SEXP tSEXP, SEXP kSEXP, SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(digt0_RDEX(t, k, l));
    return rcpp_result_gen;
END_RCPP
}
// pigt_RDEX
double pigt_RDEX(double t, double k, double l, double a, double threshold);
RcppExport SEXP _EMC2_pigt_RDEX(SEXP tSEXP, SEXP kSEXP, SEXP lSEXP, SEXP aSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(pigt_RDEX(t, k, l, a, threshold));
    return rcpp_result_gen;
END_RCPP
}
// digt_RDEX
double digt_RDEX(double t, double k, double l, double a, double threshold);
RcppExport SEXP _EMC2_digt_RDEX(SEXP tSEXP, SEXP kSEXP, SEXP lSEXP, SEXP aSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(digt_RDEX(t, k, l, a, threshold));
    return rcpp_result_gen;
END_RCPP
}
// dWald_RDEX
NumericVector dWald_RDEX(NumericVector t, double v, double B, double A, double t0);
RcppExport SEXP _EMC2_dWald_RDEX(SEXP tSEXP, SEXP vSEXP, SEXP BSEXP, SEXP ASEXP, SEXP t0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type t0(t0SEXP);
    rcpp_result_gen = Rcpp::wrap(dWald_RDEX(t, v, B, A, t0));
    return rcpp_result_gen;
END_RCPP
}
// pWald_RDEX
NumericVector pWald_RDEX(NumericVector t, double v, double B, double A, double t0);
RcppExport SEXP _EMC2_pWald_RDEX(SEXP tSEXP, SEXP vSEXP, SEXP BSEXP, SEXP ASEXP, SEXP t0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type t0(t0SEXP);
    rcpp_result_gen = Rcpp::wrap(pWald_RDEX(t, v, B, A, t0));
    return rcpp_result_gen;
END_RCPP
}
// dRDEXrace
NumericVector dRDEXrace(NumericMatrix dt, double mu, double sigma, double tau, NumericVector v, NumericVector B, NumericVector A, NumericVector t0, bool exgWinner);
RcppExport SEXP _EMC2_dRDEXrace(SEXP dtSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP tauSEXP, SEXP vSEXP, SEXP BSEXP, SEXP ASEXP, SEXP t0SEXP, SEXP exgWinnerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< bool >::type exgWinner(exgWinnerSEXP);
    rcpp_result_gen = Rcpp::wrap(dRDEXrace(dt, mu, sigma, tau, v, B, A, t0, exgWinner));
    return rcpp_result_gen;
END_RCPP
}
// stopfn_rdex
NumericVector stopfn_rdex(NumericVector t, int n_acc, double mu, double sigma, double tau, NumericVector v, NumericVector B, NumericVector A, NumericVector t0, double SSD);
RcppExport SEXP _EMC2_stopfn_rdex(SEXP tSEXP, SEXP n_accSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP tauSEXP, SEXP vSEXP, SEXP BSEXP, SEXP ASEXP, SEXP t0SEXP, SEXP SSDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type n_acc(n_accSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< double >::type SSD(SSDSEXP);
    rcpp_result_gen = Rcpp::wrap(stopfn_rdex(t, n_acc, mu, sigma, tau, v, B, A, t0, SSD));
    return rcpp_result_gen;
END_RCPP
}
// fft_convolve_equiv_cpp
arma::vec fft_convolve_equiv_cpp(const arma::vec& x, const arma::vec& y, bool conj_flag);
RcppExport SEXP _EMC2_fft_convolve_equiv_cpp(SEXP xSEXP, SEXP ySEXP, SEXP conj_flagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type conj_flag(conj_flagSEXP);
    rcpp_result_gen = Rcpp::wrap(fft_convolve_equiv_cpp(x, y, conj_flag));
    return rcpp_result_gen;
END_RCPP
}
// compute_gamma_diff_hrf
NumericVector compute_gamma_diff_hrf(double tr, int oversampling, double time_length, double onset, double delay, double undershoot, double dispersion, double u_dispersion, double ratio);
RcppExport SEXP _EMC2_compute_gamma_diff_hrf(SEXP trSEXP, SEXP oversamplingSEXP, SEXP time_lengthSEXP, SEXP onsetSEXP, SEXP delaySEXP, SEXP undershootSEXP, SEXP dispersionSEXP, SEXP u_dispersionSEXP, SEXP ratioSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tr(trSEXP);
    Rcpp::traits::input_parameter< int >::type oversampling(oversamplingSEXP);
    Rcpp::traits::input_parameter< double >::type time_length(time_lengthSEXP);
    Rcpp::traits::input_parameter< double >::type onset(onsetSEXP);
    Rcpp::traits::input_parameter< double >::type delay(delaySEXP);
    Rcpp::traits::input_parameter< double >::type undershoot(undershootSEXP);
    Rcpp::traits::input_parameter< double >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< double >::type u_dispersion(u_dispersionSEXP);
    Rcpp::traits::input_parameter< double >::type ratio(ratioSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_gamma_diff_hrf(tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio));
    return rcpp_result_gen;
END_RCPP
}
// compute_hrf
NumericVector compute_hrf(double tr, int oversampling, double time_length, double onset, double delay, double undershoot, double dispersion, double u_dispersion, double ratio);
RcppExport SEXP _EMC2_compute_hrf(SEXP trSEXP, SEXP oversamplingSEXP, SEXP time_lengthSEXP, SEXP onsetSEXP, SEXP delaySEXP, SEXP undershootSEXP, SEXP dispersionSEXP, SEXP u_dispersionSEXP, SEXP ratioSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tr(trSEXP);
    Rcpp::traits::input_parameter< int >::type oversampling(oversamplingSEXP);
    Rcpp::traits::input_parameter< double >::type time_length(time_lengthSEXP);
    Rcpp::traits::input_parameter< double >::type onset(onsetSEXP);
    Rcpp::traits::input_parameter< double >::type delay(delaySEXP);
    Rcpp::traits::input_parameter< double >::type undershoot(undershootSEXP);
    Rcpp::traits::input_parameter< double >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< double >::type u_dispersion(u_dispersionSEXP);
    Rcpp::traits::input_parameter< double >::type ratio(ratioSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_hrf(tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio));
    return rcpp_result_gen;
END_RCPP
}
// compute_time_derivative
NumericVector compute_time_derivative(double tr, int oversampling, double time_length, double onset, double delay, double undershoot, double dispersion, double u_dispersion, double ratio, double delta);
RcppExport SEXP _EMC2_compute_time_derivative(SEXP trSEXP, SEXP oversamplingSEXP, SEXP time_lengthSEXP, SEXP onsetSEXP, SEXP delaySEXP, SEXP undershootSEXP, SEXP dispersionSEXP, SEXP u_dispersionSEXP, SEXP ratioSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tr(trSEXP);
    Rcpp::traits::input_parameter< int >::type oversampling(oversamplingSEXP);
    Rcpp::traits::input_parameter< double >::type time_length(time_lengthSEXP);
    Rcpp::traits::input_parameter< double >::type onset(onsetSEXP);
    Rcpp::traits::input_parameter< double >::type delay(delaySEXP);
    Rcpp::traits::input_parameter< double >::type undershoot(undershootSEXP);
    Rcpp::traits::input_parameter< double >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< double >::type u_dispersion(u_dispersionSEXP);
    Rcpp::traits::input_parameter< double >::type ratio(ratioSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_time_derivative(tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio, delta));
    return rcpp_result_gen;
END_RCPP
}
// build_hrf_kernel
NumericMatrix build_hrf_kernel(bool has_derivative, double tr, int oversampling, double time_length, double onset, double delay, double undershoot, double dispersion, double u_dispersion, double ratio);
RcppExport SEXP _EMC2_build_hrf_kernel(SEXP has_derivativeSEXP, SEXP trSEXP, SEXP oversamplingSEXP, SEXP time_lengthSEXP, SEXP onsetSEXP, SEXP delaySEXP, SEXP undershootSEXP, SEXP dispersionSEXP, SEXP u_dispersionSEXP, SEXP ratioSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type has_derivative(has_derivativeSEXP);
    Rcpp::traits::input_parameter< double >::type tr(trSEXP);
    Rcpp::traits::input_parameter< int >::type oversampling(oversamplingSEXP);
    Rcpp::traits::input_parameter< double >::type time_length(time_lengthSEXP);
    Rcpp::traits::input_parameter< double >::type onset(onsetSEXP);
    Rcpp::traits::input_parameter< double >::type delay(delaySEXP);
    Rcpp::traits::input_parameter< double >::type undershoot(undershootSEXP);
    Rcpp::traits::input_parameter< double >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< double >::type u_dispersion(u_dispersionSEXP);
    Rcpp::traits::input_parameter< double >::type ratio(ratioSEXP);
    rcpp_result_gen = Rcpp::wrap(build_hrf_kernel(has_derivative, tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio));
    return rcpp_result_gen;
END_RCPP
}
// construct_design_matrix
DataFrame construct_design_matrix(NumericVector frame_times, DataFrame events, bool has_derivative, double min_onset, int oversampling, double time_length, double onset, double delay, double undershoot, double dispersion, double u_dispersion, double ratio, bool add_intercept);
RcppExport SEXP _EMC2_construct_design_matrix(SEXP frame_timesSEXP, SEXP eventsSEXP, SEXP has_derivativeSEXP, SEXP min_onsetSEXP, SEXP oversamplingSEXP, SEXP time_lengthSEXP, SEXP onsetSEXP, SEXP delaySEXP, SEXP undershootSEXP, SEXP dispersionSEXP, SEXP u_dispersionSEXP, SEXP ratioSEXP, SEXP add_interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type frame_times(frame_timesSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type events(eventsSEXP);
    Rcpp::traits::input_parameter< bool >::type has_derivative(has_derivativeSEXP);
    Rcpp::traits::input_parameter< double >::type min_onset(min_onsetSEXP);
    Rcpp::traits::input_parameter< int >::type oversampling(oversamplingSEXP);
    Rcpp::traits::input_parameter< double >::type time_length(time_lengthSEXP);
    Rcpp::traits::input_parameter< double >::type onset(onsetSEXP);
    Rcpp::traits::input_parameter< double >::type delay(delaySEXP);
    Rcpp::traits::input_parameter< double >::type undershoot(undershootSEXP);
    Rcpp::traits::input_parameter< double >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< double >::type u_dispersion(u_dispersionSEXP);
    Rcpp::traits::input_parameter< double >::type ratio(ratioSEXP);
    Rcpp::traits::input_parameter< bool >::type add_intercept(add_interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(construct_design_matrix(frame_times, events, has_derivative, min_onset, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio, add_intercept));
    return rcpp_result_gen;
END_RCPP
}
// get_pars_matrix_rcpp
NumericMatrix get_pars_matrix_rcpp(NumericVector p_vector, NumericVector constants, List transforms, List pretransforms, CharacterVector p_types, List designs, int n_trials, DataFrame data, List trend);
RcppExport SEXP _EMC2_get_pars_matrix_rcpp(SEXP p_vectorSEXP, SEXP constantsSEXP, SEXP transformsSEXP, SEXP pretransformsSEXP, SEXP p_typesSEXP, SEXP designsSEXP, SEXP n_trialsSEXP, SEXP dataSEXP, SEXP trendSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p_vector(p_vectorSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type constants(constantsSEXP);
    Rcpp::traits::input_parameter< List >::type transforms(transformsSEXP);
    Rcpp::traits::input_parameter< List >::type pretransforms(pretransformsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type p_types(p_typesSEXP);
    Rcpp::traits::input_parameter< List >::type designs(designsSEXP);
    Rcpp::traits::input_parameter< int >::type n_trials(n_trialsSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< List >::type trend(trendSEXP);
    rcpp_result_gen = Rcpp::wrap(get_pars_matrix_rcpp(p_vector, constants, transforms, pretransforms, p_types, designs, n_trials, data, trend));
    return rcpp_result_gen;
END_RCPP
}
// calc_ll
NumericVector calc_ll(NumericMatrix p_matrix, DataFrame data, NumericVector constants, List designs, String type_rcpp, List bounds, List transforms, List pretransforms, CharacterVector p_types, double min_ll, List trend);
RcppExport SEXP _EMC2_calc_ll(SEXP p_matrixSEXP, SEXP dataSEXP, SEXP constantsSEXP, SEXP designsSEXP, SEXP type_rcppSEXP, SEXP boundsSEXP, SEXP transformsSEXP, SEXP pretransformsSEXP, SEXP p_typesSEXP, SEXP min_llSEXP, SEXP trendSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type p_matrix(p_matrixSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type constants(constantsSEXP);
    Rcpp::traits::input_parameter< List >::type designs(designsSEXP);
    Rcpp::traits::input_parameter< String >::type type_rcpp(type_rcppSEXP);
    Rcpp::traits::input_parameter< List >::type bounds(boundsSEXP);
    Rcpp::traits::input_parameter< List >::type transforms(transformsSEXP);
    Rcpp::traits::input_parameter< List >::type pretransforms(pretransformsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type p_types(p_typesSEXP);
    Rcpp::traits::input_parameter< double >::type min_ll(min_llSEXP);
    Rcpp::traits::input_parameter< List >::type trend(trendSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_ll(p_matrix, data, constants, designs, type_rcpp, bounds, transforms, pretransforms, p_types, min_ll, trend));
    return rcpp_result_gen;
END_RCPP
}
// truncated_normal_a_cdf
double truncated_normal_a_cdf(double x, double mu, double sigma, double a);
RcppExport SEXP _EMC2_truncated_normal_a_cdf(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(truncated_normal_a_cdf(x, mu, sigma, a));
    return rcpp_result_gen;
END_RCPP
}
// truncated_normal_a_pdf
double truncated_normal_a_pdf(double x, double mu, double sigma, double a);
RcppExport SEXP _EMC2_truncated_normal_a_pdf(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(truncated_normal_a_pdf(x, mu, sigma, a));
    return rcpp_result_gen;
END_RCPP
}
// c_add_charvectors
CharacterVector c_add_charvectors(CharacterVector x, CharacterVector y);
RcppExport SEXP _EMC2_c_add_charvectors(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(c_add_charvectors(x, y));
    return rcpp_result_gen;
END_RCPP
}
// pmvnorm_cpp
NumericVector pmvnorm_cpp(NumericVector upper, NumericMatrix corr);
RcppExport SEXP _EMC2_pmvnorm_cpp(SEXP upperSEXP, SEXP corrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type corr(corrSEXP);
    rcpp_result_gen = Rcpp::wrap(pmvnorm_cpp(upper, corr));
    return rcpp_result_gen;
END_RCPP
}
// exp_decay
NumericVector exp_decay(NumericVector t, double x0, double xinf, double tau, double p);
RcppExport SEXP _EMC2_exp_decay(SEXP tSEXP, SEXP x0SEXP, SEXP xinfSEXP, SEXP tauSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< double >::type xinf(xinfSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(exp_decay(t, x0, xinf, tau, p));
    return rcpp_result_gen;
END_RCPP
}
// calculate_num_steps
int calculate_num_steps(double t_max, double fineness, int min_steps);
RcppExport SEXP _EMC2_calculate_num_steps(SEXP t_maxSEXP, SEXP finenessSEXP, SEXP min_stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t_max(t_maxSEXP);
    Rcpp::traits::input_parameter< double >::type fineness(finenessSEXP);
    Rcpp::traits::input_parameter< int >::type min_steps(min_stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_num_steps(t_max, fineness, min_steps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EMC2_pbvn_tsay", (DL_FUNC) &_EMC2_pbvn_tsay, 3},
    {"_EMC2_pbvn_tvpack", (DL_FUNC) &_EMC2_pbvn_tvpack, 3},
    {"_EMC2_pbvn_drezner", (DL_FUNC) &_EMC2_pbvn_drezner, 3},
    {"_EMC2_sp_new", (DL_FUNC) &_EMC2_sp_new, 10},
    {"_EMC2_calculate_subject_means", (DL_FUNC) &_EMC2_calculate_subject_means, 4},
    {"_EMC2_bm_fht_pdf_vec_grid", (DL_FUNC) &_EMC2_bm_fht_pdf_vec_grid, 10},
    {"_EMC2_bm_fht_pdf_vec_grid_chunked", (DL_FUNC) &_EMC2_bm_fht_pdf_vec_grid_chunked, 13},
    {"_EMC2_bm_fht_cdf_vec_grid_chunked", (DL_FUNC) &_EMC2_bm_fht_cdf_vec_grid_chunked, 14},
    {"_EMC2_bm_fht_cdf_vec_grid", (DL_FUNC) &_EMC2_bm_fht_cdf_vec_grid, 11},
    {"_EMC2_bm_fht_pdf_vec", (DL_FUNC) &_EMC2_bm_fht_pdf_vec, 9},
    {"_EMC2_bm_fht_cdf_vec", (DL_FUNC) &_EMC2_bm_fht_cdf_vec, 9},
    {"_EMC2_simulate_bm_hit_times", (DL_FUNC) &_EMC2_simulate_bm_hit_times, 10},
    {"_EMC2_simulate_bm_hit_times_bb", (DL_FUNC) &_EMC2_simulate_bm_hit_times_bb, 10},
    {"_EMC2_plba_norm", (DL_FUNC) &_EMC2_plba_norm, 7},
    {"_EMC2_dlba_norm", (DL_FUNC) &_EMC2_dlba_norm, 7},
    {"_EMC2_dlba_c", (DL_FUNC) &_EMC2_dlba_c, 7},
    {"_EMC2_plba_c", (DL_FUNC) &_EMC2_plba_c, 7},
    {"_EMC2_dlba_joint_c", (DL_FUNC) &_EMC2_dlba_joint_c, 7},
    {"_EMC2_plba_joint_c", (DL_FUNC) &_EMC2_plba_joint_c, 7},
    {"_EMC2_dlba", (DL_FUNC) &_EMC2_dlba, 6},
    {"_EMC2_plba", (DL_FUNC) &_EMC2_plba, 6},
    {"_EMC2_ou_fht_cdf", (DL_FUNC) &_EMC2_ou_fht_cdf, 10},
    {"_EMC2_ou_fht_pdf_vec", (DL_FUNC) &_EMC2_ou_fht_pdf_vec, 11},
    {"_EMC2_ou_fht_cdf_vec_grid", (DL_FUNC) &_EMC2_ou_fht_cdf_vec_grid, 13},
    {"_EMC2_ou_fht_pdf_vec_spline", (DL_FUNC) &_EMC2_ou_fht_pdf_vec_spline, 11},
    {"_EMC2_ou_fht_cdf_vec", (DL_FUNC) &_EMC2_ou_fht_cdf_vec, 10},
    {"_EMC2_ou_fht_pdf_vec_closed_form", (DL_FUNC) &_EMC2_ou_fht_pdf_vec_closed_form, 9},
    {"_EMC2_ou_fht_cdf_vec_closed_form", (DL_FUNC) &_EMC2_ou_fht_cdf_vec_closed_form, 9},
    {"_EMC2_ou_fht_pdf_vec_grid", (DL_FUNC) &_EMC2_ou_fht_pdf_vec_grid, 12},
    {"_EMC2_ou_fht_pdf_vec_grid_chunked", (DL_FUNC) &_EMC2_ou_fht_pdf_vec_grid_chunked, 15},
    {"_EMC2_simulate_ou_hit_times_std", (DL_FUNC) &_EMC2_simulate_ou_hit_times_std, 11},
    {"_EMC2_ou_fht_cdf_vec_grid_chunked", (DL_FUNC) &_EMC2_ou_fht_cdf_vec_grid_chunked, 16},
    {"_EMC2_simulate_ou_hit_times", (DL_FUNC) &_EMC2_simulate_ou_hit_times, 11},
    {"_EMC2_simulate_ou_hit_times_bb", (DL_FUNC) &_EMC2_simulate_ou_hit_times_bb, 15},
    {"_EMC2_pigt0", (DL_FUNC) &_EMC2_pigt0, 4},
    {"_EMC2_digt0", (DL_FUNC) &_EMC2_digt0, 4},
    {"_EMC2_dwald_classic", (DL_FUNC) &_EMC2_dwald_classic, 4},
    {"_EMC2_pwald_classic", (DL_FUNC) &_EMC2_pwald_classic, 4},
    {"_EMC2_pigt", (DL_FUNC) &_EMC2_pigt, 6},
    {"_EMC2_digt", (DL_FUNC) &_EMC2_digt, 6},
    {"_EMC2_drdm_c", (DL_FUNC) &_EMC2_drdm_c, 6},
    {"_EMC2_prdm_c", (DL_FUNC) &_EMC2_prdm_c, 6},
    {"_EMC2_dRDM_c", (DL_FUNC) &_EMC2_dRDM_c, 6},
    {"_EMC2_pRDM_c", (DL_FUNC) &_EMC2_pRDM_c, 6},
    {"_EMC2_dswtn", (DL_FUNC) &_EMC2_dswtn, 5},
    {"_EMC2_pswtn", (DL_FUNC) &_EMC2_pswtn, 5},
    {"_EMC2_drdmswtn", (DL_FUNC) &_EMC2_drdmswtn, 7},
    {"_EMC2_prdmswtn", (DL_FUNC) &_EMC2_prdmswtn, 7},
    {"_EMC2_dSWTNspv", (DL_FUNC) &_EMC2_dSWTNspv, 7},
    {"_EMC2_pSWTNspv", (DL_FUNC) &_EMC2_pSWTNspv, 7},
    {"_EMC2_drdmswtn_c", (DL_FUNC) &_EMC2_drdmswtn_c, 6},
    {"_EMC2_prdmswtn_c", (DL_FUNC) &_EMC2_prdmswtn_c, 6},
    {"_EMC2_pswtn_numeric_integral", (DL_FUNC) &_EMC2_pswtn_numeric_integral, 7},
    {"_EMC2_drdmswtn_numeric_integral", (DL_FUNC) &_EMC2_drdmswtn_numeric_integral, 8},
    {"_EMC2_prdmswtn_numeric_integral", (DL_FUNC) &_EMC2_prdmswtn_numeric_integral, 8},
    {"_EMC2_pEXG", (DL_FUNC) &_EMC2_pEXG, 6},
    {"_EMC2_dEXG", (DL_FUNC) &_EMC2_dEXG, 5},
    {"_EMC2_dEXGrace", (DL_FUNC) &_EMC2_dEXGrace, 4},
    {"_EMC2_stopfn_exg", (DL_FUNC) &_EMC2_stopfn_exg, 5},
    {"_EMC2_pEXG_RDEX", (DL_FUNC) &_EMC2_pEXG_RDEX, 6},
    {"_EMC2_dEXG_RDEX", (DL_FUNC) &_EMC2_dEXG_RDEX, 5},
    {"_EMC2_pigt0_RDEX", (DL_FUNC) &_EMC2_pigt0_RDEX, 3},
    {"_EMC2_digt0_RDEX", (DL_FUNC) &_EMC2_digt0_RDEX, 3},
    {"_EMC2_pigt_RDEX", (DL_FUNC) &_EMC2_pigt_RDEX, 5},
    {"_EMC2_digt_RDEX", (DL_FUNC) &_EMC2_digt_RDEX, 5},
    {"_EMC2_dWald_RDEX", (DL_FUNC) &_EMC2_dWald_RDEX, 5},
    {"_EMC2_pWald_RDEX", (DL_FUNC) &_EMC2_pWald_RDEX, 5},
    {"_EMC2_dRDEXrace", (DL_FUNC) &_EMC2_dRDEXrace, 9},
    {"_EMC2_stopfn_rdex", (DL_FUNC) &_EMC2_stopfn_rdex, 10},
    {"_EMC2_fft_convolve_equiv_cpp", (DL_FUNC) &_EMC2_fft_convolve_equiv_cpp, 3},
    {"_EMC2_compute_gamma_diff_hrf", (DL_FUNC) &_EMC2_compute_gamma_diff_hrf, 9},
    {"_EMC2_compute_hrf", (DL_FUNC) &_EMC2_compute_hrf, 9},
    {"_EMC2_compute_time_derivative", (DL_FUNC) &_EMC2_compute_time_derivative, 10},
    {"_EMC2_build_hrf_kernel", (DL_FUNC) &_EMC2_build_hrf_kernel, 10},
    {"_EMC2_construct_design_matrix", (DL_FUNC) &_EMC2_construct_design_matrix, 13},
    {"_EMC2_get_pars_matrix_rcpp", (DL_FUNC) &_EMC2_get_pars_matrix_rcpp, 9},
    {"_EMC2_calc_ll", (DL_FUNC) &_EMC2_calc_ll, 11},
    {"_EMC2_truncated_normal_a_cdf", (DL_FUNC) &_EMC2_truncated_normal_a_cdf, 4},
    {"_EMC2_truncated_normal_a_pdf", (DL_FUNC) &_EMC2_truncated_normal_a_pdf, 4},
    {"_EMC2_c_add_charvectors", (DL_FUNC) &_EMC2_c_add_charvectors, 2},
    {"_EMC2_pmvnorm_cpp", (DL_FUNC) &_EMC2_pmvnorm_cpp, 2},
    {"_EMC2_exp_decay", (DL_FUNC) &_EMC2_exp_decay, 5},
    {"_EMC2_calculate_num_steps", (DL_FUNC) &_EMC2_calculate_num_steps, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_EMC2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
