# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sp_new <- function(iter, lambda_varimax, q, p, dim_all_c, all_c, lambda_hat, st, cost_matrix, perm) {
    .Call(`_EMC2_sp_new`, iter, lambda_varimax, q, p, dim_all_c, all_c, lambda_hat, st, cost_matrix, perm)
}

calculate_subject_means <- function(group_designs, params, n_subjects, n_pars) {
    .Call(`_EMC2_calculate_subject_means`, group_designs, params, n_subjects, n_pars)
}

dlba <- function(t, A, b, v, sv, posdrift = TRUE) {
    .Call(`_EMC2_dlba`, t, A, b, v, sv, posdrift)
}

plba <- function(t, A, b, v, sv, posdrift = TRUE) {
    .Call(`_EMC2_plba`, t, A, b, v, sv, posdrift)
}

dlba_vec <- function(t, A, b, v, sv, posdrift = TRUE) {
    .Call(`_EMC2_dlba_vec`, t, A, b, v, sv, posdrift)
}

plba_vec <- function(t, A, b, v, sv, posdrift = TRUE) {
    .Call(`_EMC2_plba_vec`, t, A, b, v, sv, posdrift)
}

pigt0 <- function(t, k = 1., l = 1.) {
    .Call(`_EMC2_pigt0`, t, k, l)
}

dwald <- function(t, boundary_alpha, drift_rate_xi) {
    .Call(`_EMC2_dwald`, t, boundary_alpha, drift_rate_xi)
}

pwald <- function(t, boundary_alpha, drift_rate_xi) {
    .Call(`_EMC2_pwald`, t, boundary_alpha, drift_rate_xi)
}

digt0 <- function(t, k = 1., l = 1.) {
    .Call(`_EMC2_digt0`, t, k, l)
}

pigt <- function(t, k = 1, l = 1, a = .1, threshold = 1e-10) {
    .Call(`_EMC2_pigt`, t, k, l, a, threshold)
}

digt <- function(t, k = 1., l = 1., a = .1, threshold = 1e-10) {
    .Call(`_EMC2_digt`, t, k, l, a, threshold)
}

drdm_c <- function(rts, pars, idx, min_ll, is_ok) {
    .Call(`_EMC2_drdm_c`, rts, pars, idx, min_ll, is_ok)
}

prdm_c <- function(rts, pars, idx, min_ll, is_ok) {
    .Call(`_EMC2_prdm_c`, rts, pars, idx, min_ll, is_ok)
}

dWald <- function(t, v, B, A, t0) {
    .Call(`_EMC2_dWald`, t, v, B, A, t0)
}

pWald <- function(t, v, B, A, t0) {
    .Call(`_EMC2_pWald`, t, v, B, A, t0)
}

truncated_normal_pdf <- function(xi, mu, sigma_sq, lower_bound = 0) {
    .Call(`_EMC2_truncated_normal_pdf`, xi, mu, sigma_sq, lower_bound)
}

dswtn <- function(t_adj, alpha, mu_drift, sigma_drift_sq) {
    .Call(`_EMC2_dswtn`, t_adj, alpha, mu_drift, sigma_drift_sq)
}

pswtn <- function(t_adj, alpha, mu_drift, sigma_drift_sq, abs_err = 1e-6, rel_err = 1e-6, max_eval = 1000L) {
    .Call(`_EMC2_pswtn`, t_adj, alpha, mu_drift, sigma_drift_sq, abs_err, rel_err, max_eval)
}

rtnorm_rng_positive <- function(mu, sigma_sq) {
    .Call(`_EMC2_rtnorm_rng_positive`, mu, sigma_sq)
}

rinvgauss_rng <- function(mu_ig, lambda_ig) {
    .Call(`_EMC2_rinvgauss_rng`, mu_ig, lambda_ig)
}

rswtn <- function(alpha, mu_drift, sigma_drift_sq, theta) {
    .Call(`_EMC2_rswtn`, alpha, mu_drift, sigma_drift_sq, theta)
}

swtn_spv_logpdf <- function(t_adj, k_center, A_spv, mu_drift, sigma_drift_sq, abs_err = 1e-6, rel_err = 1e-6, max_eval = 1000L) {
    .Call(`_EMC2_swtn_spv_logpdf`, t_adj, k_center, A_spv, mu_drift, sigma_drift_sq, abs_err, rel_err, max_eval)
}

swtn_spv_cdf <- function(t_adj, k_center, A_spv, mu_drift, sigma_drift_sq, abs_err = 1e-6, rel_err = 1e-6, max_eval = 1000L) {
    .Call(`_EMC2_swtn_spv_cdf`, t_adj, k_center, A_spv, mu_drift, sigma_drift_sq, abs_err, rel_err, max_eval)
}

drdmswtn <- function(t_adj, B, A, mu_drift, sigma_drift_sq, spv_abs_err = 1e-6, spv_rel_err = 1e-6, spv_max_eval = 1000L) {
    .Call(`_EMC2_drdmswtn`, t_adj, B, A, mu_drift, sigma_drift_sq, spv_abs_err, spv_rel_err, spv_max_eval)
}

prdmswtn <- function(t_adj, B, A, mu_drift, sigma_drift_sq, spv_abs_err = 1e-6, spv_rel_err = 1e-6, spv_max_eval = 1000L) {
    .Call(`_EMC2_prdmswtn`, t_adj, B, A, mu_drift, sigma_drift_sq, spv_abs_err, spv_rel_err, spv_max_eval)
}

dRDM_SWTN <- function(t, B, A, mu_drift, sigma_drift_sq, t0, s) {
    .Call(`_EMC2_dRDM_SWTN`, t, B, A, mu_drift, sigma_drift_sq, t0, s)
}

pRDM_SWTN <- function(t, B, A, mu_drift, sigma_drift_sq, t0, s, spv_abs_err = 1e-6, spv_rel_err = 1e-6, spv_max_eval = 1000L) {
    .Call(`_EMC2_pRDM_SWTN`, t, B, A, mu_drift, sigma_drift_sq, t0, s, spv_abs_err, spv_rel_err, spv_max_eval)
}

rRDM_SWTN <- function(n_samples, B, A, mu_drift, sigma_drift_sq, t0, s = 1.0) {
    .Call(`_EMC2_rRDM_SWTN`, n_samples, B, A, mu_drift, sigma_drift_sq, t0, s)
}

pEXG <- function(q, mu = 5., sigma = 1., tau = 1., lower_tail = TRUE, log_p = FALSE) {
    .Call(`_EMC2_pEXG`, q, mu, sigma, tau, lower_tail, log_p)
}

dEXG <- function(x, mu = 5., sigma = 1., tau = 1., log_d = FALSE) {
    .Call(`_EMC2_dEXG`, x, mu, sigma, tau, log_d)
}

dEXGrace <- function(dt, mu, sigma, tau) {
    .Call(`_EMC2_dEXGrace`, dt, mu, sigma, tau)
}

stopfn_exg <- function(t, mu, sigma, tau, SSD) {
    .Call(`_EMC2_stopfn_exg`, t, mu, sigma, tau, SSD)
}

pEXG_RDEX <- function(q, mu = 5., sigma = 1., tau = 1., lower_tail = TRUE, log_p = FALSE) {
    .Call(`_EMC2_pEXG_RDEX`, q, mu, sigma, tau, lower_tail, log_p)
}

dEXG_RDEX <- function(x, mu = 5., sigma = 1., tau = 1., log_d = FALSE) {
    .Call(`_EMC2_dEXG_RDEX`, x, mu, sigma, tau, log_d)
}

pigt0_RDEX <- function(t, k = 1., l = 1.) {
    .Call(`_EMC2_pigt0_RDEX`, t, k, l)
}

digt0_RDEX <- function(t, k = 1., l = 1.) {
    .Call(`_EMC2_digt0_RDEX`, t, k, l)
}

pigt_RDEX <- function(t, k = 1, l = 1, a = .1, threshold = 1e-10) {
    .Call(`_EMC2_pigt_RDEX`, t, k, l, a, threshold)
}

digt_RDEX <- function(t, k = 1., l = 1., a = .1, threshold = 1e-10) {
    .Call(`_EMC2_digt_RDEX`, t, k, l, a, threshold)
}

dWald_RDEX <- function(t, v, B, A, t0) {
    .Call(`_EMC2_dWald_RDEX`, t, v, B, A, t0)
}

pWald_RDEX <- function(t, v, B, A, t0) {
    .Call(`_EMC2_pWald_RDEX`, t, v, B, A, t0)
}

dRDEXrace <- function(dt, mu, sigma, tau, v, B, A, t0, exgWinner = TRUE) {
    .Call(`_EMC2_dRDEXrace`, dt, mu, sigma, tau, v, B, A, t0, exgWinner)
}

stopfn_rdex <- function(t, n_acc, mu, sigma, tau, v, B, A, t0, SSD) {
    .Call(`_EMC2_stopfn_rdex`, t, n_acc, mu, sigma, tau, v, B, A, t0, SSD)
}

fft_convolve_equiv_cpp <- function(x, y, conj_flag = TRUE) {
    .Call(`_EMC2_fft_convolve_equiv_cpp`, x, y, conj_flag)
}

compute_gamma_diff_hrf <- function(tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio) {
    .Call(`_EMC2_compute_gamma_diff_hrf`, tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio)
}

compute_hrf <- function(tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio) {
    .Call(`_EMC2_compute_hrf`, tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio)
}

compute_time_derivative <- function(tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio, delta = 0.1) {
    .Call(`_EMC2_compute_time_derivative`, tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio, delta)
}

build_hrf_kernel <- function(has_derivative, tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio) {
    .Call(`_EMC2_build_hrf_kernel`, has_derivative, tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio)
}

construct_design_matrix <- function(frame_times, events, has_derivative, min_onset, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio, add_intercept) {
    .Call(`_EMC2_construct_design_matrix`, frame_times, events, has_derivative, min_onset, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio, add_intercept)
}

calc_ll <- function(p_matrix, data, constants, designs, type_rcpp, bounds, transforms, pretransforms, p_types, min_ll, trend) {
    .Call(`_EMC2_calc_ll`, p_matrix, data, constants, designs, type_rcpp, bounds, transforms, pretransforms, p_types, min_ll, trend)
}

test_c_loglik_cens_trunc_wrapper_R <- function(pars, dadm, model_type_str, min_ll, ok_params, n_acc, R_model_obj_list) {
    .Call(`_EMC2_test_c_loglik_cens_trunc_wrapper_R`, pars, dadm, model_type_str, min_ll, ok_params, n_acc, R_model_obj_list)
}

c_add_charvectors <- function(x, y) {
    .Call(`_EMC2_c_add_charvectors`, x, y)
}

