# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sp_new <- function(iter, lambda_varimax, q, p, dim_all_c, all_c, lambda_hat, st, cost_matrix, perm) {
    .Call(`_EMC2_sp_new`, iter, lambda_varimax, q, p, dim_all_c, all_c, lambda_hat, st, cost_matrix, perm)
}

calculate_subject_means <- function(group_designs, params, n_subjects, n_pars) {
    .Call(`_EMC2_calculate_subject_means`, group_designs, params, n_subjects, n_pars)
}

dlba <- function(t, A, b, v, sv, posdrift = TRUE) {
    .Call(`_EMC2_dlba`, t, A, b, v, sv, posdrift)
}

plba <- function(t, A, b, v, sv, posdrift = TRUE) {
    .Call(`_EMC2_plba`, t, A, b, v, sv, posdrift)
}

pigt0 <- function(t, k = 1., l = 1.) {
    .Call(`_EMC2_pigt0`, t, k, l)
}

digt0 <- function(t, k = 1., l = 1.) {
    .Call(`_EMC2_digt0`, t, k, l)
}

dwald_classic <- function(t, boundary_alpha, drift_rate_xi) {
    .Call(`_EMC2_dwald_classic`, t, boundary_alpha, drift_rate_xi)
}

pwald_classic <- function(t, boundary_alpha, drift_rate_xi) {
    .Call(`_EMC2_pwald_classic`, t, boundary_alpha, drift_rate_xi)
}

pigt <- function(t, k = 1, l = 1, a = .1, threshold = 1e-10) {
    .Call(`_EMC2_pigt`, t, k, l, a, threshold)
}

digt <- function(t, k = 1., l = 1., a = .1, threshold = 1e-10) {
    .Call(`_EMC2_digt`, t, k, l, a, threshold)
}

drdm_c <- function(rts, pars, idx, min_ll, is_ok) {
    .Call(`_EMC2_drdm_c`, rts, pars, idx, min_ll, is_ok)
}

prdm_c <- function(rts, pars, idx, min_ll, is_ok) {
    .Call(`_EMC2_prdm_c`, rts, pars, idx, min_ll, is_ok)
}

dRDM_c <- function(t, v, B, A, t0) {
    .Call(`_EMC2_dRDM_c`, t, v, B, A, t0)
}

pRDM_c <- function(t, v, B, A, t0) {
    .Call(`_EMC2_pRDM_c`, t, v, B, A, t0)
}

dswtn <- function(t_adj, alpha, mu_drift, sigma_drift) {
    .Call(`_EMC2_dswtn`, t_adj, alpha, mu_drift, sigma_drift)
}

pswtn <- function(t_adj, alpha, mu_drift, sigma_drift) {
    .Call(`_EMC2_pswtn`, t_adj, alpha, mu_drift, sigma_drift)
}

drdmswtn <- function(t_adj, B, mu_drift, A, sigma_drift, n_gauss_nodes = 20L) {
    .Call(`_EMC2_drdmswtn`, t_adj, B, mu_drift, A, sigma_drift, n_gauss_nodes)
}

prdmswtn <- function(t_adj, B, mu_drift, A, sigma_drift, n_gauss_nodes = 20L) {
    .Call(`_EMC2_prdmswtn`, t_adj, B, mu_drift, A, sigma_drift, n_gauss_nodes)
}

dSWTNspv <- function(t, v, B, A, t0, sv) {
    .Call(`_EMC2_dSWTNspv`, t, v, B, A, t0, sv)
}

pSWTNspv <- function(t, v, B, A, t0, sv) {
    .Call(`_EMC2_pSWTNspv`, t, v, B, A, t0, sv)
}

drdmswtn_c <- function(rts, pars, idx, min_ll, is_ok) {
    .Call(`_EMC2_drdmswtn_c`, rts, pars, idx, min_ll, is_ok)
}

prdmswtn_c <- function(rts, pars, idx, min_ll, is_ok) {
    .Call(`_EMC2_prdmswtn_c`, rts, pars, idx, min_ll, is_ok)
}

pEXG <- function(q, mu = 5., sigma = 1., tau = 1., lower_tail = TRUE, log_p = FALSE) {
    .Call(`_EMC2_pEXG`, q, mu, sigma, tau, lower_tail, log_p)
}

dEXG <- function(x, mu = 5., sigma = 1., tau = 1., log_d = FALSE) {
    .Call(`_EMC2_dEXG`, x, mu, sigma, tau, log_d)
}

dEXGrace <- function(dt, mu, sigma, tau) {
    .Call(`_EMC2_dEXGrace`, dt, mu, sigma, tau)
}

stopfn_exg <- function(t, mu, sigma, tau, SSD) {
    .Call(`_EMC2_stopfn_exg`, t, mu, sigma, tau, SSD)
}

pEXG_RDEX <- function(q, mu = 5., sigma = 1., tau = 1., lower_tail = TRUE, log_p = FALSE) {
    .Call(`_EMC2_pEXG_RDEX`, q, mu, sigma, tau, lower_tail, log_p)
}

dEXG_RDEX <- function(x, mu = 5., sigma = 1., tau = 1., log_d = FALSE) {
    .Call(`_EMC2_dEXG_RDEX`, x, mu, sigma, tau, log_d)
}

pigt0_RDEX <- function(t, k = 1., l = 1.) {
    .Call(`_EMC2_pigt0_RDEX`, t, k, l)
}

digt0_RDEX <- function(t, k = 1., l = 1.) {
    .Call(`_EMC2_digt0_RDEX`, t, k, l)
}

pigt_RDEX <- function(t, k = 1, l = 1, a = .1, threshold = 1e-10) {
    .Call(`_EMC2_pigt_RDEX`, t, k, l, a, threshold)
}

digt_RDEX <- function(t, k = 1., l = 1., a = .1, threshold = 1e-10) {
    .Call(`_EMC2_digt_RDEX`, t, k, l, a, threshold)
}

dWald_RDEX <- function(t, v, B, A, t0) {
    .Call(`_EMC2_dWald_RDEX`, t, v, B, A, t0)
}

pWald_RDEX <- function(t, v, B, A, t0) {
    .Call(`_EMC2_pWald_RDEX`, t, v, B, A, t0)
}

dRDEXrace <- function(dt, mu, sigma, tau, v, B, A, t0, exgWinner = TRUE) {
    .Call(`_EMC2_dRDEXrace`, dt, mu, sigma, tau, v, B, A, t0, exgWinner)
}

stopfn_rdex <- function(t, n_acc, mu, sigma, tau, v, B, A, t0, SSD) {
    .Call(`_EMC2_stopfn_rdex`, t, n_acc, mu, sigma, tau, v, B, A, t0, SSD)
}

fft_convolve_equiv_cpp <- function(x, y, conj_flag = TRUE) {
    .Call(`_EMC2_fft_convolve_equiv_cpp`, x, y, conj_flag)
}

compute_gamma_diff_hrf <- function(tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio) {
    .Call(`_EMC2_compute_gamma_diff_hrf`, tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio)
}

compute_hrf <- function(tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio) {
    .Call(`_EMC2_compute_hrf`, tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio)
}

compute_time_derivative <- function(tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio, delta = 0.1) {
    .Call(`_EMC2_compute_time_derivative`, tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio, delta)
}

build_hrf_kernel <- function(has_derivative, tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio) {
    .Call(`_EMC2_build_hrf_kernel`, has_derivative, tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio)
}

construct_design_matrix <- function(frame_times, events, has_derivative, min_onset, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio, add_intercept) {
    .Call(`_EMC2_construct_design_matrix`, frame_times, events, has_derivative, min_onset, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio, add_intercept)
}

get_pars_matrix_rcpp <- function(p_vector, constants, transforms, pretransforms, p_types, designs, n_trials, data, trend) {
    .Call(`_EMC2_get_pars_matrix_rcpp`, p_vector, constants, transforms, pretransforms, p_types, designs, n_trials, data, trend)
}

calc_ll <- function(p_matrix, data, constants, designs, type_rcpp, bounds, transforms, pretransforms, p_types, min_ll, trend) {
    .Call(`_EMC2_calc_ll`, p_matrix, data, constants, designs, type_rcpp, bounds, transforms, pretransforms, p_types, min_ll, trend)
}

truncated_normal_a_cdf <- function(x, mu, sigma, a) {
    .Call(`_EMC2_truncated_normal_a_cdf`, x, mu, sigma, a)
}

truncated_normal_a_cdf_inv <- function(cdf, mu, sigma, a) {
    .Call(`_EMC2_truncated_normal_a_cdf_inv`, cdf, mu, sigma, a)
}

truncated_normal_a_mean <- function(mu, sigma, a) {
    .Call(`_EMC2_truncated_normal_a_mean`, mu, sigma, a)
}

truncated_normal_a_moment <- function(order, mu, sigma, a) {
    .Call(`_EMC2_truncated_normal_a_moment`, order, mu, sigma, a)
}

truncated_normal_a_pdf <- function(x, mu, sigma, a) {
    .Call(`_EMC2_truncated_normal_a_pdf`, x, mu, sigma, a)
}

truncated_normal_a_sample <- function(mu, sigma, a, seed) {
    .Call(`_EMC2_truncated_normal_a_sample`, mu, sigma, a, seed)
}

truncated_normal_a_variance <- function(mu, sigma, a) {
    .Call(`_EMC2_truncated_normal_a_variance`, mu, sigma, a)
}

c_add_charvectors <- function(x, y) {
    .Call(`_EMC2_c_add_charvectors`, x, y)
}

pmvnorm_cpp <- function(upper, corr) {
    .Call(`_EMC2_pmvnorm_cpp`, upper, corr)
}

pbivnorm_fast <- function(h, k, rho) {
    .Call(`_EMC2_pbivnorm_fast`, h, k, rho)
}

