# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sp_new <- function(iter, lambda_varimax, q, p, dim_all_c, all_c, lambda_hat, st, cost_matrix, perm) {
    .Call(`_EMC2_sp_new`, iter, lambda_varimax, q, p, dim_all_c, all_c, lambda_hat, st, cost_matrix, perm)
}

calculate_subject_means <- function(group_designs, params, n_subjects, n_pars) {
    .Call(`_EMC2_calculate_subject_means`, group_designs, params, n_subjects, n_pars)
}

bm_fht_pdf_vec_grid <- function(t, mu, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps) {
    .Call(`_EMC2_bm_fht_pdf_vec_grid`, t, mu, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps)
}

bm_fht_pdf_vec_grid_chunked <- function(t, mu, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps, chunk_ratio, chunk_base_panels, chunk_max) {
    .Call(`_EMC2_bm_fht_pdf_vec_grid_chunked`, t, mu, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps, chunk_ratio, chunk_base_panels, chunk_max)
}

bm_fht_cdf_vec_grid_chunked <- function(t, mu, sigma, z0, b0, binf, tau, pow, steps_fineness = 0.005, min_steps = 300, chunk_ratio = 1.5, chunk_base_panels = 500, chunk_max = 12, rt_resolution = NA_real_) {
    .Call(`_EMC2_bm_fht_cdf_vec_grid_chunked`, t, mu, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps, chunk_ratio, chunk_base_panels, chunk_max, rt_resolution)
}

bm_fht_cdf_vec_grid <- function(t, mu, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps, rt_resolution = NA_real_) {
    .Call(`_EMC2_bm_fht_cdf_vec_grid`, t, mu, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps, rt_resolution)
}

bm_fht_pdf_vec <- function(t, mu, sigma, z0, b0, binf, tau, pow, num_steps = 200L) {
    .Call(`_EMC2_bm_fht_pdf_vec`, t, mu, sigma, z0, b0, binf, tau, pow, num_steps)
}

bm_fht_cdf_vec <- function(t, mu, sigma, z0, b0, binf, tau, pow, num_steps = 200L) {
    .Call(`_EMC2_bm_fht_cdf_vec`, t, mu, sigma, z0, b0, binf, tau, pow, num_steps)
}

simulate_bm_hit_times <- function(n, mu, sigma, z0, b0, binf, tau = 1.0, pow = 1.0, dt = 1e-3, t_max = 10.0) {
    .Call(`_EMC2_simulate_bm_hit_times`, n, mu, sigma, z0, b0, binf, tau, pow, dt, t_max)
}

simulate_bm_hit_times_bb <- function(n, mu, sigma, z0, b0, binf, tau = 1.0, pow = 1.0, dt = 1e-3, t_max = 10.0, p_tol = 1e-9, eps_curv = 0.1, adapt_factor = 32.0, adaptive = TRUE) {
    .Call(`_EMC2_simulate_bm_hit_times_bb`, n, mu, sigma, z0, b0, binf, tau, pow, dt, t_max, p_tol, eps_curv, adapt_factor, adaptive)
}

simulate_gbm_hit_times_bb <- function(n, mu, sigma, z0, b0, binf, tau = 1.0, pow = 1.0, dt = 1e-3, t_max = 10.0, start_floor = 1, p_tol = 1e-9, eps_curv = 0.1, adapt_factor = 32.0, adaptive = TRUE) {
    .Call(`_EMC2_simulate_gbm_hit_times_bb`, n, mu, sigma, z0, b0, binf, tau, pow, dt, t_max, start_floor, p_tol, eps_curv, adapt_factor, adaptive)
}

plba_norm <- function(t, A, b, v, sv, posdrift = TRUE, log_out = FALSE) {
    .Call(`_EMC2_plba_norm`, t, A, b, v, sv, posdrift, log_out)
}

dlba_norm <- function(t, A, b, v, sv, posdrift = TRUE, log_out = FALSE) {
    .Call(`_EMC2_dlba_norm`, t, A, b, v, sv, posdrift, log_out)
}

dlba_c <- function(rts, pars, idx, min_ll, is_ok, use_posdrift = TRUE, log_out = FALSE) {
    .Call(`_EMC2_dlba_c`, rts, pars, idx, min_ll, is_ok, use_posdrift, log_out)
}

plba_c <- function(rts, pars, idx, min_ll, is_ok, use_posdrift = TRUE, log_out = FALSE) {
    .Call(`_EMC2_plba_c`, rts, pars, idx, min_ll, is_ok, use_posdrift, log_out)
}

dlba_joint_c <- function(rts, pars, idx, min_ll, is_ok, use_posdrift = TRUE, log_out = FALSE) {
    .Call(`_EMC2_dlba_joint_c`, rts, pars, idx, min_ll, is_ok, use_posdrift, log_out)
}

plba_joint_c <- function(rts, pars, idx, min_ll, is_ok, use_posdrift = TRUE, log_out = FALSE) {
    .Call(`_EMC2_plba_joint_c`, rts, pars, idx, min_ll, is_ok, use_posdrift, log_out)
}

dlba <- function(t, A, b, v, sv, posdrift = TRUE) {
    .Call(`_EMC2_dlba`, t, A, b, v, sv, posdrift)
}

plba <- function(t, A, b, v, sv, posdrift = TRUE) {
    .Call(`_EMC2_plba`, t, A, b, v, sv, posdrift)
}

ou_fht_cdf <- function(t, lambda, theta, sigma, z0, b0, binf, tau, p, num_steps) {
    .Call(`_EMC2_ou_fht_cdf`, t, lambda, theta, sigma, z0, b0, binf, tau, p, num_steps)
}

ou_fht_pdf_vec <- function(t, lambda, theta, sigma, z0, b0, binf, tau, pow, steps_fineness = 0.005, min_steps = 300) {
    .Call(`_EMC2_ou_fht_pdf_vec`, t, lambda, theta, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps)
}

ou_fht_cdf_vec_grid <- function(t, lambda, theta, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps, min_t_fineness, rt_resolution = 0.02) {
    .Call(`_EMC2_ou_fht_cdf_vec_grid`, t, lambda, theta, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps, min_t_fineness, rt_resolution)
}

ou_fht_cdf_vec <- function(t, lambda, theta, sigma, z0, b0, binf, tau, pow, num_steps = 200L) {
    .Call(`_EMC2_ou_fht_cdf_vec`, t, lambda, theta, sigma, z0, b0, binf, tau, pow, num_steps)
}

ou_fht_pdf_vec_closed_form <- function(t, lambda, theta, sigma, z0, b0, binf, tau = 1.0, pow = 1.0) {
    .Call(`_EMC2_ou_fht_pdf_vec_closed_form`, t, lambda, theta, sigma, z0, b0, binf, tau, pow)
}

ou_fht_cdf_vec_closed_form <- function(t, lambda, theta, sigma, z0, b0, binf, tau = 1.0, pow = 1.0) {
    .Call(`_EMC2_ou_fht_cdf_vec_closed_form`, t, lambda, theta, sigma, z0, b0, binf, tau, pow)
}

ou_fht_pdf_vec_grid <- function(t, lambda, theta, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps, min_t_fineness) {
    .Call(`_EMC2_ou_fht_pdf_vec_grid`, t, lambda, theta, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps, min_t_fineness)
}

ou_fht_pdf_vec_grid_chunked <- function(t, lambda, theta, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps, min_t_fineness, chunk_ratio, chunk_base_panels, chunk_max) {
    .Call(`_EMC2_ou_fht_pdf_vec_grid_chunked`, t, lambda, theta, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps, min_t_fineness, chunk_ratio, chunk_base_panels, chunk_max)
}

ou_fht_cdf_vec_grid_chunked <- function(t, lambda, theta, sigma, z0, b0, binf, tau, pow, steps_fineness = 0.005, min_steps = 300, min_t_fineness = 0.001, chunk_ratio = 1.5, chunk_base_panels = 500, chunk_max = 12, rt_resolution = 0.02) {
    .Call(`_EMC2_ou_fht_cdf_vec_grid_chunked`, t, lambda, theta, sigma, z0, b0, binf, tau, pow, steps_fineness, min_steps, min_t_fineness, chunk_ratio, chunk_base_panels, chunk_max, rt_resolution)
}

simulate_ou_hit_times <- function(n, lambda, theta, sigma, z0, b0, binf, tau = 1.0, p = 1.0, dt = 1e-3, t_max = 10.0) {
    .Call(`_EMC2_simulate_ou_hit_times`, n, lambda, theta, sigma, z0, b0, binf, tau, p, dt, t_max)
}

simulate_ou_hit_times_bb <- function(n, lambda, theta, sigma, z0, b0, binf, tau = 1.0, p = 1.0, dt = 1e-3, t_max = 10.0, p_tol = 1e-9, eps_curv = 0.1, adapt_factor = 32.0, adaptive = TRUE) {
    .Call(`_EMC2_simulate_ou_hit_times_bb`, n, lambda, theta, sigma, z0, b0, binf, tau, p, dt, t_max, p_tol, eps_curv, adapt_factor, adaptive)
}

simulate_gompertz_hit_times_bb <- function(n, alpha, beta, z0, k0, kinf, tau = 1.0, pow = 1.0, dt = 1e-3, t_max = 10.0, start_floor = 1e-3, p_tol = 1e-9, eps_curv = 0.1, adapt_factor = 32.0, adaptive = TRUE) {
    .Call(`_EMC2_simulate_gompertz_hit_times_bb`, n, alpha, beta, z0, k0, kinf, tau, pow, dt, t_max, start_floor, p_tol, eps_curv, adapt_factor, adaptive)
}

pigt0 <- function(t, k = 1.0, l = 1.0, log_out = FALSE) {
    .Call(`_EMC2_pigt0`, t, k, l, log_out)
}

digt0 <- function(t, k = 1.0, l = 1.0, log_out = FALSE) {
    .Call(`_EMC2_digt0`, t, k, l, log_out)
}

dwald <- function(t, b, mu, sigma = 1, A = 0, log_out = FALSE) {
    .Call(`_EMC2_dwald`, t, b, mu, sigma, A, log_out)
}

dgbm <- function(t, b, mu, sigma, A, log_out = FALSE) {
    .Call(`_EMC2_dgbm`, t, b, mu, sigma, A, log_out)
}

pwald <- function(t, b, mu, sigma, A, log_out = FALSE) {
    .Call(`_EMC2_pwald`, t, b, mu, sigma, A, log_out)
}

pgbm <- function(t, b, mu, sigma, A, log_out = FALSE) {
    .Call(`_EMC2_pgbm`, t, b, mu, sigma, A, log_out)
}

pigt <- function(t, k = 1, l = 1, a = .1, threshold = 1e-10, log_out = FALSE) {
    .Call(`_EMC2_pigt`, t, k, l, a, threshold, log_out)
}

digt <- function(t, k = 1., l = 1., a = .1, threshold = 1e-10, log_out = FALSE) {
    .Call(`_EMC2_digt`, t, k, l, a, threshold, log_out)
}

drdm_c <- function(rts, pars, idx, min_ll, is_ok, log_out = FALSE) {
    .Call(`_EMC2_drdm_c`, rts, pars, idx, min_ll, is_ok, log_out)
}

prdm_c <- function(rts, pars, idx, min_ll, is_ok, log_out = FALSE) {
    .Call(`_EMC2_prdm_c`, rts, pars, idx, min_ll, is_ok, log_out)
}

dRDM_c <- function(t, v, B, A, t0, log_out = FALSE) {
    .Call(`_EMC2_dRDM_c`, t, v, B, A, t0, log_out)
}

pRDM_c <- function(t, v, B, A, t0, log_out = FALSE) {
    .Call(`_EMC2_pRDM_c`, t, v, B, A, t0, log_out)
}

dswtn <- function(t_adj, alpha, mu_drift, sv, s = 1.0, c = 0.0, log_out = FALSE) {
    .Call(`_EMC2_dswtn`, t_adj, alpha, mu_drift, sv, s, c, log_out)
}

pswtn <- function(t_adj, alpha, mu_drift, sv, s = 1.0, c = 0.0, log_out = FALSE) {
    .Call(`_EMC2_pswtn`, t_adj, alpha, mu_drift, sv, s, c, log_out)
}

drdmswtn <- function(t_adj, b, mu_drift, A, sv, s = 1.0, c = 0.0, n_gauss_nodes = 20L, log_out = FALSE) {
    .Call(`_EMC2_drdmswtn`, t_adj, b, mu_drift, A, sv, s, c, n_gauss_nodes, log_out)
}

prdmswtn <- function(t_adj, b, mu_drift, A, sv, s = 1.0, c = 0.0, n_gauss_nodes = 20L, log_out = FALSE) {
    .Call(`_EMC2_prdmswtn`, t_adj, b, mu_drift, A, sv, s, c, n_gauss_nodes, log_out)
}

dSWTNspv <- function(t, v, b, A, t0, sv, s = 1.0, c = 0.0, log_out = FALSE) {
    .Call(`_EMC2_dSWTNspv`, t, v, b, A, t0, sv, s, c, log_out)
}

pSWTNspv <- function(t, v, b, A, t0, sv, s = 1.0, c = 0.0, log_out = FALSE) {
    .Call(`_EMC2_pSWTNspv`, t, v, b, A, t0, sv, s, c, log_out)
}

drdmswtn_c <- function(rts, pars, idx, min_ll, is_ok, log_out = FALSE) {
    .Call(`_EMC2_drdmswtn_c`, rts, pars, idx, min_ll, is_ok, log_out)
}

prdmswtn_c <- function(rts, pars, idx, min_ll, is_ok, log_out = FALSE) {
    .Call(`_EMC2_prdmswtn_c`, rts, pars, idx, min_ll, is_ok, log_out)
}

dWALDspv <- function(t, b, v, sigma, A, t0, log_out = FALSE) {
    .Call(`_EMC2_dWALDspv`, t, b, v, sigma, A, t0, log_out)
}

dGBMspv <- function(t, b, v, sigma, A, t0, log_out = FALSE) {
    .Call(`_EMC2_dGBMspv`, t, b, v, sigma, A, t0, log_out)
}

pWALDspv <- function(t, b, v, sigma, A, t0, log_out = FALSE) {
    .Call(`_EMC2_pWALDspv`, t, b, v, sigma, A, t0, log_out)
}

pGBMspv <- function(t, b, v, sigma, A, t0, log_out = FALSE) {
    .Call(`_EMC2_pGBMspv`, t, b, v, sigma, A, t0, log_out)
}

pEXG <- function(q, mu = 5., sigma = 1., tau = 1., lower_tail = TRUE, log_p = FALSE) {
    .Call(`_EMC2_pEXG`, q, mu, sigma, tau, lower_tail, log_p)
}

dEXG <- function(x, mu = 5., sigma = 1., tau = 1., log_d = FALSE) {
    .Call(`_EMC2_dEXG`, x, mu, sigma, tau, log_d)
}

dEXGrace <- function(dt, mu, sigma, tau) {
    .Call(`_EMC2_dEXGrace`, dt, mu, sigma, tau)
}

stopfn_exg <- function(t, mu, sigma, tau, SSD) {
    .Call(`_EMC2_stopfn_exg`, t, mu, sigma, tau, SSD)
}

pEXG_RDEX <- function(q, mu = 5., sigma = 1., tau = 1., lower_tail = TRUE, log_p = FALSE) {
    .Call(`_EMC2_pEXG_RDEX`, q, mu, sigma, tau, lower_tail, log_p)
}

dEXG_RDEX <- function(x, mu = 5., sigma = 1., tau = 1., log_d = FALSE) {
    .Call(`_EMC2_dEXG_RDEX`, x, mu, sigma, tau, log_d)
}

pigt0_RDEX <- function(t, k = 1., l = 1.) {
    .Call(`_EMC2_pigt0_RDEX`, t, k, l)
}

digt0_RDEX <- function(t, k = 1., l = 1.) {
    .Call(`_EMC2_digt0_RDEX`, t, k, l)
}

pigt_RDEX <- function(t, k = 1, l = 1, a = .1, threshold = 1e-10) {
    .Call(`_EMC2_pigt_RDEX`, t, k, l, a, threshold)
}

digt_RDEX <- function(t, k = 1., l = 1., a = .1, threshold = 1e-10) {
    .Call(`_EMC2_digt_RDEX`, t, k, l, a, threshold)
}

dWald_RDEX <- function(t, v, B, A, t0) {
    .Call(`_EMC2_dWald_RDEX`, t, v, B, A, t0)
}

pWald_RDEX <- function(t, v, B, A, t0) {
    .Call(`_EMC2_pWald_RDEX`, t, v, B, A, t0)
}

dRDEXrace <- function(dt, mu, sigma, tau, v, B, A, t0, exgWinner = TRUE) {
    .Call(`_EMC2_dRDEXrace`, dt, mu, sigma, tau, v, B, A, t0, exgWinner)
}

stopfn_rdex <- function(t, n_acc, mu, sigma, tau, v, B, A, t0, SSD) {
    .Call(`_EMC2_stopfn_rdex`, t, n_acc, mu, sigma, tau, v, B, A, t0, SSD)
}

fft_convolve_equiv_cpp <- function(x, y, conj_flag = TRUE) {
    .Call(`_EMC2_fft_convolve_equiv_cpp`, x, y, conj_flag)
}

compute_gamma_diff_hrf <- function(tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio) {
    .Call(`_EMC2_compute_gamma_diff_hrf`, tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio)
}

compute_hrf <- function(tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio) {
    .Call(`_EMC2_compute_hrf`, tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio)
}

compute_time_derivative <- function(tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio, delta = 0.1) {
    .Call(`_EMC2_compute_time_derivative`, tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio, delta)
}

build_hrf_kernel <- function(has_derivative, tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio) {
    .Call(`_EMC2_build_hrf_kernel`, has_derivative, tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio)
}

construct_design_matrix <- function(frame_times, events, has_derivative, min_onset, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio, add_intercept) {
    .Call(`_EMC2_construct_design_matrix`, frame_times, events, has_derivative, min_onset, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio, add_intercept)
}

get_pars_matrix_rcpp <- function(p_vector, constants, transforms, pretransforms, p_types, designs, n_trials, data, trend) {
    .Call(`_EMC2_get_pars_matrix_rcpp`, p_vector, constants, transforms, pretransforms, p_types, designs, n_trials, data, trend)
}

calc_ll <- function(p_matrix, data, constants, designs, type_rcpp, bounds, transforms, pretransforms, p_types, min_ll, trend) {
    .Call(`_EMC2_calc_ll`, p_matrix, data, constants, designs, type_rcpp, bounds, transforms, pretransforms, p_types, min_ll, trend)
}

truncated_normal_a_cdf <- function(x, mu, sigma, a) {
    .Call(`_EMC2_truncated_normal_a_cdf`, x, mu, sigma, a)
}

truncated_normal_a_pdf <- function(x, mu, sigma, a) {
    .Call(`_EMC2_truncated_normal_a_pdf`, x, mu, sigma, a)
}

c_add_charvectors <- function(x, y) {
    .Call(`_EMC2_c_add_charvectors`, x, y)
}

pmvnorm_cpp <- function(upper, corr) {
    .Call(`_EMC2_pmvnorm_cpp`, upper, corr)
}

exp_decay <- function(t, x0, xinf, tau, p) {
    .Call(`_EMC2_exp_decay`, t, x0, xinf, tau, p)
}

pbvn_tsay <- function(h, k, rho) {
    .Call(`_EMC2_pbvn_tsay`, h, k, rho)
}

pbvn_tvpack <- function(h, k, rho) {
    .Call(`_EMC2_pbvn_tvpack`, h, k, rho)
}

pbvn_drezner <- function(h, k, rho) {
    .Call(`_EMC2_pbvn_drezner`, h, k, rho)
}

ou_debug_set <- function(enabled = TRUE, level = 1L) {
    invisible(.Call(`_EMC2_ou_debug_set`, enabled, level))
}

calculate_num_steps <- function(t_max, fineness = 0.01, min_steps = 100L) {
    .Call(`_EMC2_calculate_num_steps`, t_max, fineness, min_steps)
}

